### ISSUE TITLE
Doesnt show Calendar

### ISSUE THREAD

**Issue by leovipin1** [osTicket/osTicket-1.7#102]
Hi,

When I click the advanced option to search for a ticket, it shows an option for date range, but when i click the calendar icon it doesnt show the calendar

**Comment by protich** [comment]
We have a pull request pending to resolve the issue. To get the latest code you'll need to intall/switch to develop branch instead of master.

PS. Please note that development is by no means complete.  Some features are still in the pipeline.

**Comment by greezybacon** [comment]
leovipin1, can you verify that it works now in the latest develop branch?

**Comment by leovipin1** [comment]
the calendar is showing up now

**Comment by satvirdogra** [comment]
Hi 

Is calender View not available in 1.8?

Thanks
