### ISSUE TITLE
Shows only one ticket

### ISSUE THREAD

**Issue by leovipin1** [osTicket/osTicket-1.7#106]
Hi,

When I try to check the status of any ticket through the client side, i login using the email address and the particular ticket number. It shows only that particular ticket, but not all the tickets that have been created by the particular email address.

**Comment by olondono** [comment]
System Preferences and Settings -> Ticket Settings and Options -> Show Related Tickets.

**Comment by protich** [comment]
The default behavior is to show related tickets - but as of v1.7 admin can limit access per ticket.
