### ISSUE TITLE
Strict Standards: Non-static method

### ISSUE THREAD

**Issue by mark05e** [osTicket/osTicket-1.7#113]
Hi,

I get the following error when I try testing this:

Strict Standards: Non-static method Validator::process() should not be called statically, assuming $this from incompatible context in C:\UniServer_new\www\osticket\setup\inc\class.installer.php on line 63 Strict Standards: Non-static method Passwd::hash() should not be called statically, assuming $this from incompatible context in C:\UniServer_new\www\osticket\setup\inc\class.installer.php on line 125 Strict Standards: Non-static method Misc::randCode() should not be called statically, assuming $this from incompatible context in C:\UniServer_new\www\osticket\setup\inc\class.installer.php on line 155 Strict Standards: Non-static method Misc::randNumber() should not be called statically, assuming $this from incompatible context in C:\UniServer_new\www\osticket\setup\inc\class.installer.php on line 175

Strict Standards: Non-static method Misc::currentURL() should not be called statically in C:\UniServer_new\www\osticket\main.inc.php on line 103 Strict Standards: Non-static method Sys::getConfig() should not be called statically in C:\UniServer_new\www\osticket\main.inc.php on line 160 Strict Standards: Non-static method osTicketSession::start() should not be called statically in C:\UniServer_new\www\osticket\main.inc.php on line 176

This shows up on almost all the pages.

**Comment by mark05e** [comment]
Can be fixed by modifying error_reporting function in the files **osticket\main.inc.php** and **osticket\setup\setup.inc.php**

Needs to set it to the code below:

**error_reporting(E_ALL ^ E_NOTICE ^ E_STRICT);**

I think this issue from php 5.4.x onwards (http://in2.php.net/manual/en/function.error-reporting.php) and I am using Unifrom Server 8.5.4 for the test.

_(I have no programming experience btw :P)_

**Comment by greezybacon** [comment]
This should be fixed with issue #125

**Comment by greezybacon** [comment]
Bump

**Comment by greezybacon** [comment]
Can this be closed?
