### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by marksie1988** [osTicket/osTicket-1.7#121]
Add a reporting system that allows you to set criteria and run reports on that criteria

this is a major downfall of this system, we like to do reports per customer that allows us to know if the customer needs to be paying more. 

Without reports the system is limited for viewing statistics on support tickets etc.

**Comment by protich** [comment]
Jared - OK to close? Reports per customer will be a good addition but not for 1.7 rc1.

**Comment by greezybacon** [comment]
Stats Per customer would be an easy mod. Close it if you want to do it for support system first. Leave it open otherwise.

We basically just would add another tab with the stats table and show stats by client email.

**Comment by protich** [comment]
I'll leave it open for now. I wasn't implying that it was hard to do nor is it a reserved feature. 

That said, we'll need to rethink where such reports need to go - paginating hundreds or thousands of users on the current reports interface will be a mess and almost useless (in the context of system wide overview).  My thinking is such reports needs to come in after adding customer/clients tab.

**Comment by greezybacon** [comment]
I agree. You're the visionary. If 1.7 isn't the platform, let's close it and think through how this should be properly implemented in the future
