### ISSUE TITLE
"php" missing in include/client/view.inc.php on line 99

### ISSUE THREAD

**Issue by stevehal** [osTicket/osTicket-1.7#122]
If you get an unexpected $end in the view.inc.php, and you have short tags off, simply go into line 99 (it may be 100 as it shows line 100 on my install but it shows 99 here on github) and change the <? to <?php and it will fix the error!

A leftover from not requiring short tags.

**Comment by stevehal** [comment]
Same on line 108 in include/staff/faq.inc.php

**Comment by greezybacon** [comment]
Did you observe this after switching to the 'develop' branch?

**Comment by stevehal** [comment]
Hi Greezy... sorry for the delay.

I just downloaded the full 1.7-dpr3 "zipball" archive and installed it. I think just a few <? sneaked in without the php.

No big deal as I set the short tags flag. In fact, in 1.7-dpr4 I did not see this when I checked the file. So it looks OK now!
