### ISSUE TITLE
config canFetchMail() is using the wrong config variable?

### ISSUE THREAD

**Issue by baskettcase** [osTicket/osTicket-1.7#123]
I think it should be the 'enable_mail_polling' config variable, not the 'enable_mail_fetch' or 'enable_fetch_mail', I don't remember what I changed it from :)

**Comment by greezybacon** [comment]
The only place I see the old variable ('enable_mail_fetch') used is in include/staff/preference.inc.php, which is no longer used anymore. I would like to fix this issue by removing that file. Is there somewhere else you saw the old variable used at?

**Comment by baskettcase** [comment]
In include/class.config.php in the canFetchMail() method.

**Comment by greezybacon** [comment]
I show that was fixed in c44c823ba34cc48fef4ecb7f5b21a6b114b0270e on April 26. Did you forget to do a `git pull`?

**Comment by baskettcase** [comment]
Looks like it was fixed. Very possible I installed before that date, I didn't think I had.. but it does look ok in the latest pull, so great! :)
