### ISSUE TITLE
Count and view category in kb

### ISSUE THREAD

**Issue by mikhey54** [osTicket/osTicket-1.7#13]
for correct view and count Category on /kb/index.php please add this:
## file        knowledgebase.inc.php

line 16     .' LEFT JOIN '.FAQ_TABLE.' faq USING(category_id) '
## \+       .' WHERE cat.ispublic=1 '

---

line 92     .' WHERE cat.ispublic=1 '

**Comment by mikhey54** [comment]
this fix for include / client / knowledgebase.inc.php

**Comment by protich** [comment]
Thanks for the report - Client interface is still under heavy development - let's focus on SCP for now.
