### ISSUE TITLE
Created tickets don't show up

### ISSUE THREAD

**Issue by OSPHPChat** [osTicket/osTicket-1.7#130]
When you create a ticket through the admin panel they don't show up on the index or tickets.php. v1.7-DPR3

**Comment by greezybacon** [comment]
This is a browser cache issue. We need to figure out what other header(s) need to be sent to convince the browser not to cache a dynamic PHP page

**Comment by kurim** [comment]
Possible workaround, to disable the cache functions through header
/include/client/header.inc.php
/include/staff/header.inc.php

add this lines

```
<?php
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: no-store, no-cache, must-revalidate",true);
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
?>
```

**Comment by leovipin1** [comment]
Facing the same Issue in every browser for ex: Mozilla, IE and chrome

**Comment by leovipin1** [comment]
This same issue is persisting in DPRv4 as well

**Comment by greezybacon** [comment]
The cache issue was resolved with #146. Can you confirm this works properly now?

**Comment by OSPHPChat** [comment]
This is now fixed.

Thank you. :)

**Comment by greezybacon** [comment]
Awsum. Good to hear!
