### ISSUE TITLE
admin link not working

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket-1.7#132]
After you fixed the issue of the installer i redownload all the file and it worked great it let me install however i did notice something i am not sure were the issue is but when i login and click on the admin link at top right  it just keeps logging me out.. not sure if you guys are having the same issue or not but throught i would report this also

once it logs me out the web address looks like this www.example.com/support//scp/syslogs.php

**Comment by ghost** [comment]
i did 2 clean installs with 2 new sql databases and for some reason when trying to acccess the admin panel it will not let me.

**Comment by greezybacon** [comment]
Are you sure this isn't a browser cache issue?

**Comment by ghost** [comment]
acually now that u mention it, i cleared the browser cache and then retried it and i still had the same problem, so then i tried a different browser and it worked fine....

i cant explain it but it logs you out like i mentioned if you have firefox 13

but i tried in internet explorer 9 and it worked

i also tested in google chrome and opera and it worked in them also i am not sure why it is not working in firefox
