### ISSUE TITLE
how to upgrade from 1.6ST?

### ISSUE THREAD

**Issue by bensig** [osTicket/osTicket-1.7#133]
I uploaded my files, copied my ost-config.php to the correct directory, but update.php is blank and my logs don't have any useful errors... ideas?

**Comment by protich** [comment]
**Upgrade from 1.6 will be supported starting with 1.7 RC1.**

osTicket 1.7 DPR is pre-release software, in active development, that may be substantially changed before it's packaged for public release. It is NOT recommended for production environments nor recommended for upgrading existing installations.

**Comment by bensig** [comment]
How close are we to getting RC1?

**Comment by greezybacon** [comment]
Upgrading from 1.6 is now supported from the `develop` branch. Feel free to start testing any time. **Beware that upgrading is potentially error prone.** Make a backup before you get started. _Although I hope it works for you with a hitch_

**Comment by bensig** [comment]
You know, I will test it out eventually. We ended up installing Request Tracker since it supported replies by email. 

Are you planning on integrating that in the future?

**Comment by greezybacon** [comment]
@protich says don't count on it. It doesn't make sense for osTicket.
