### ISSUE TITLE
Autoassign

### ISSUE THREAD

**Issue by kurim** [osTicket/osTicket-1.7#137]
Incoming tickets by email will be set to department but not group.
So group member will not get Mail or cant even see the ticket.

Example:

ticket@test.de => assign to depa X

The mail to member of depa X will get the email but cant accsess cause it will not assign to the Group,
is their a way to fix it.

From my point mails to depa mails should be also assigneable to group after get the email.

^fh

**Comment by greezybacon** [comment]
I think #161 implemented this feature. Can you confirm if you're able to do this with the latest `develop` branch?

**Comment by greezybacon** [comment]
Can this be closed?

**Comment by kurim** [comment]
Yes, thank you.
