### ISSUE TITLE
open ticket and view ticket buttons

### ISSUE THREAD

**Issue by scmb** [osTicket/osTicket-1.7#14]
I know you guys are in the development stage and i didnt know if you guys wanted any type of suggestions but i thought i would make a slight suggestion for an enhancement

On the client side were the 2 buttons  are the blue and green ones,  their is currently no animation to let users know they are clicking on the buttons,  its just an image currently...

I think it would  be nicer if you used css and you will be able to get the same look of the current  buttons.

For example if you do something simular like github does,   after you click on open new issue at the bottom their is the faded green button,  but when you hover over it, it turns darker green.

**Comment by mikhey54** [comment]
Very nice button's :)

**Comment by kellishaver** [comment]
buttons have been redone. :)
