### ISSUE TITLE
PDF exporting (ticket print) does not handle non-ascii characters well

### ISSUE THREAD

**Issue by greezybacon** [osTicket/osTicket-1.7#160]
Output appears to be interpreted by the PDF as ascii characters, when the database is sourcing UTF-8 encoded text

**Comment by mikhey54** [comment]
And don't support russian fonts :(
Please add russian fonts for PDF exporting

**Comment by greezybacon** [comment]
@mikhey54, can you comment if this helps russian chars encoded in UTF-8?
