### ISSUE TITLE
< symbols

### ISSUE THREAD

**Issue by tecklee** [osTicket/osTicket-1.7#162]
When posting replies, either publicly or internal notes, adding the following symbols will cause the message to be truncated and not displayed:

```
<) 
```

For example, adding this response will cause truncation on 1.6:

"Hello there. There is an extra "less than" (<) symbol in your code"

Thank you.

**Comment by greezybacon** [comment]
This does not seem to be an issue for osTicket-1.7. 

Can you confirm that this bug still exists in 1.7?

**Comment by tecklee** [comment]
Hi Jared,

Thank you for looking into this. 

Yes, this is on our production 1.6 system. Have not tried on 1.7. 

Thank you and keep up the good work. 

Teck Lee
Singapore

**Comment by OSPHPChat** [comment]
I tried this with v1.7-DPR4 and it truncated the message. This was before https://github.com/osTicket/osTicket-1.7/pull/166 was added. Will try the new code in a bit.
