### ISSUE TITLE
Replying to a ticket message outputs as Array

### ISSUE THREAD

**Issue by howdu** [osTicket/osTicket-1.7#167]
class.ticket.php -> line 1338

It appears as though variable $msg is getting over written by:
$msg_tpl=$tpl->getNewMessageAlertMsgTemplate();

Fixed by replace following code:
if($cfg->alertONNewMessage() && $tpl && $email && ($_msg=$tpl->getNewMessageAlertMsgTemplate())) {

```
        $body=$this->replaceTemplateVars($_msg['body']);
        $subj=$this->replaceTemplateVars($_msg['subj']);
        $body = str_replace("%message", $msg,$body);
```

**Comment by soif** [comment]
fixed in RC1:
https://github.com/osTicket/osTicket-1.7/commit/c6bdc7e3f8c9bec50286366ebdba075c19adbcfe
