### ISSUE TITLE
Feature: Allow easy design hooks, update-proof

### ISSUE THREAD

**Issue by soif** [osTicket/osTicket-1.7#177]
I would like to implement a feature allowing osticket users to easily add some custom HTML to staff or client pages (mainly for the header and footers part).

IMHO  a typical users of osTicket (as any other Web script), want to easily adapt it , to his own website branding. He obvioulsy also want this to be update proof. 
Currently he have to hack various header.inc and footer.in pages, which may changes at each osTicktet update (this is a pain for him).

Adding a few line of codes, could make his life really easier:

Here is an example of (dummy) code to help you better understand what I mean:

in header.inc.php, AT start:

if(file_exist(ost-custom.php)){
    $custom=array();
    include(ost-custom.php);
}

then in the &lt;HEAD&gt; tag, at the end "echo $custom['scp_head']"
then further, in the # wrapper DIV,  "echo $custom['scp_header']"

then in the footer.inc.php file,  "echo $custom['scp_footer']"

The ost-custom.php file could then hold something like:
  $custom['scp_head']   ="&lt;link type='text/css' href='my_custom.css' &gt;&lt;script href='my_custom.js' &gt;&lt;/script&gt;";
  $custom['scp_header']="&lt;div id='_my_site_header' &gt;xxxxx&lt;div &gt;";
  $custom['scp_footer']  ="&lt;div id='_my_site_footer' &gt;zzzzzzzz&lt;div &gt;";

This combined with consistent  CSS classes on various osTicket pages, would allow anyome to easily build their own design by filling their ost-custom.php file (copied from a ost-custom-dist.php example file), overriding CSS rules, adding JS functions, inserting their header/footer HTML to any page of osTicket, without breaking all their custom design modifications upon each osTicket release update.

What you think?
If you're OK, Where to put the ost-custom-dist.php file (in includes)?

**Comment by protich** [comment]
We plan on implementing themes and plugins down the road, among other features like multilingual support. For now, we're focusing on pushing 1.7 out.

I don't necessarily agree on your implementation, but that is a discussion for another day. That said, you're welcome to implement it as you see fit but don't assume the mod will be accepted.

**Comment by soif** [comment]
"my implementation", should certainly be discussed (a lot), It's just a really draft idea.

I just think that adding a very easy to use  custom file (ost-custom.php) right away (in 1.7), even if it's not fully and beautifully implemented, would pave the way for  users , to easily work on their own basic branding (head,header,footer) while surviving osTicket updates.

Let's resume for now (1.7). The Idea is: lets just have a config file with and array of at least head,header,footer, echoed in some basic HTML places, (only if the custom file exists). 
We will then have the time until v1.8, to discuss if we move this to a sql database, if we either split it in more files, etc... But in the meantime, users, will have a clean place to do their own basic design, WITHOUT compromising the main code.

I'm pretty sure that users would LOVE it, even if it's just really basic includes at this time!

**Comment by protich** [comment]
I rather have no feature than half-baked hack...that has been a guiding policy in osTicket development.
