### ISSUE TITLE
Knowledgebase don't view in user interface

### ISSUE THREAD

**Issue by mikhey54** [osTicket/osTicket-1.7#184]
RC1 -> Knowledgebase don't view in user interface

**Comment by soif** [comment]
did you activate it from the admin setting page?

"Helpdesk Status:   Online"

**Comment by mikhey54** [comment]
This option default active in admin setting page  !!!

**Comment by protich** [comment]
For knowledge base to be **active** you must have it _enabled_ **AND** have at least one published FAQ.

**Comment by mikhey54** [comment]
protich, ok

**Comment by bravogon** [comment]
Hi 
I did what protich said and I still can not see my Knowledgebase link in my interface page.
I installed osTicket in my own server would that be a problem?
