### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by protich** [osTicket/osTicket-1.7#188]
Add LDAP support

**Comment by josh1856** [comment]
how do I add the ldap code to the branch?

**Comment by protich** [comment]
http://git-scm.com/documentation 
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by josh1856** [comment]
Again try the following we have used it multiple times internally for php based applications.
http://code.google.com/p/ldap-auth-php/

**Comment by jeffchulg** [comment]
Question : should the osTicket admin account be authentificated through LDAP ?

**Comment by josh1856** [comment]
I personally believe that the admin account should not AUTH through the LDAP, however, the admin account can be changed based on the user so it may make sense to AUTH the admin.  Peter may have some better input.

**Comment by protich** [comment]
My thoughts:
- LDAP settings should be configurable via Admin Panel
- Multiple LDAP support - think different domains..etc
- It should be opt-in instead of out-out - setting on staff page.

**Comment by greezybacon** [comment]
LDAP is implemented in osTicket 1.8.1 with the auth-ldap plugin available in the osTicket/core-plugins repo or from the osticket.com download page.
