### ISSUE TITLE
Dashboard IE8 Error 

### ISSUE THREAD

**Issue by protich** [osTicket/osTicket-1.7#189]
@mambobrown 

> One of my clients use IE8 as thier default internal browser and while testing the 1.7 rc version of the software ran into a problem >with the dashboard working properly. They are getting a error. The error is as follows: Line:119 Char: 59 Error: Expected >identifier, string or number Code: 0 URL: http://~/osticket/scp/dashboard.php

**Comment by matmattia** [comment]
Edit line 118 of "scp/js/dashboard.inc.js" in this way:

``` javascript
.append($('<li>').attr((first) ? {'class':'active'} : {})
```
