### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by soif** [osTicket/osTicket-1.7#194]
Trying to put an header() , in various place of the code most often results in "Headers already sent". 
IMO, this is due to remaining CR or spaces after the closing "?;gt;" php tag in a lot of included files.

Would you like me to fix this?

**Comment by protich** [comment]
We use header() in a couple places with no issues at all. You're welcome to hunt down the issue.

**Comment by soif** [comment]
Hunting it could be really long and absolutely boring, but removing all remaining space after the ?&gt; in all includes, is generally accepted as a good practice, to prevent these sort of issues. 
And if you're OK with this, i could clean most of the files, this way.
