### ISSUE TITLE
Ticket merge

### ISSUE THREAD

**Issue by josh1856** [osTicket/osTicket-1.7#206]
Ability to merge multiple tickets together.

**Comment by josh1856** [comment]
These links may help...
http://osticket.com/forums/showthread.php?t=2462&page=2
http://www.openscriptsolution.com/2009/11/03/add-merge-ticket-feature-into-osticket-v1-6-rc5/

**Comment by OgundareIbukun** [comment]
hi, @josh185. None of these links are working any longer.  Can you please share your solution here.

**Comment by Richiricheh** [comment]
@OgundareIbukun  osTicket forums have a search feature....

I assume this is what you're looking for:
https://forum.osticket.com/d/89699-osticket-v110-merge-duplicate-ticket-mods-attached (MOD based on 1.10)

I'd also like to point out that one of the DEVs on this git pull responded:

https://github.com/osTicket/osTicket/pull/3768#issuecomment-478061838

It appears that they will be adding this feature into Core "soon....ish"  lol
