### ISSUE TITLE
Default sorting on tickets

### ISSUE THREAD

**Issue by josh1856** [osTicket/osTicket-1.7#212]
The ability to set the default sorting in the user preferences on the open tickets page.  For instance set the default to sort by ticket id, date received or department.

**Comment by josh1856** [comment]
Is there any adverse affect to changing the "Date Format:" setting in "Date & Time Options" if someone wanted to view tickets in the open tickets tab by date and time?  For instance changing the "Date Format:" setting to "m/d/Y g:i a"?  Maybe it would make sense to explain what that changes or to rename the field?

**Comment by protich** [comment]
See issue #204 for sorting option.
