### ISSUE TITLE
Sort ticket thread asc AND desc by date capabilities

### ISSUE THREAD

**Issue by jeffchulg** [osTicket/osTicket-1.7#224]
When one wants to get directly to the last comment made on a ticket, he has to go to the end of the ticket thread. If there was a capability to sort ticket thread descending by date of creation, this problem would be solved. 
There also could be the possibility to set system/user default sorting preference.

**Comment by soif** [comment]
would you like this way?

**Comment by jeffchulg** [comment]
as you want, the principle is that you get access to the lastest messages easily
