### ISSUE TITLE
Ticket ID and Auth-Code Expiration.

### ISSUE THREAD

**Issue by protich** [osTicket/osTicket-1.7#227]
This is a continued discussion, from #223,  on the need to expire ticket ID and `%auth` code.

**Comment by soif** [comment]
protish wrote:

> As for your google bot scenario - you're making the assumption that the user WILL somehow leak the emailed link to google.
> 
> Why would a user submit the emailed link to google?

A competitor could, or most probably  a spammer will (liking to get a link posted in the ticked)
Also putting rel=nofollow on every user submitted link would also not hurt ;-)

> Having adsense on the page doesn't leak the link - it's an emailed link and page redirects on auto-login. Please clarify.

You're right, if the auth page does'nt post anything on screen (no adsense) Google wont see it.

But if the OST user change the web ticket OK message to display something like "Your ticket as been successfully posted. You can watch it at %auth_url" and if the page has any adSense on it, booom, google get the link!

> I'm not against adding some kind of timeout - but it should be a setting admin can enable/change.

For sure! some setting like "auth links expire days (set to 0 to disable)"

**Comment by protich** [comment]
You're making stuff up - sorry but have to be blunt.
- The only way a competitor or spammer can get hold of the link is by breaking into your email account. Nothing we can do about that... Exposed email & ticket ID (due to hacked email account) are sufficient to login - even without %auth code.  Can they post their own link? Yes - but that is an issue we can address with noindex & nofollow.  
- Adsense bot **=/=** Google bot - the former just does contextual matches for the purpose of displaying ads. Adding Adsense doesn't mean the "link" will show up in google search. Once again the link is emailed.
- osTicket **doesn't** display `%auth_link` or even `%ticket` (Ticket ID) on thank you page.  Displaying it could potentially allow third-party to gain access to user's tickets - given how osTicket authenticates users. **BUT** that is a different issue and not related at all to Adsense in your scenario (see above).
- Can a user or admin somehow expose the link or ticket Id?  Yes. Will timeout solve the issue? No.

Once again I'm not opposed to adding a configurable validity period/timeout. I just want to make sure we're doing it for the right reasons to solve/address a particular issue(s)/problem(s).

PS: Adding noindex and nofollow makes sense.

**Comment by soif** [comment]
> Adsense bot =/= Google bot - the former just does contextual matches for the purpose of displaying ads. Adding >Adsense doesn't mean the "link" will show up in google search

No! Google Adsense bot sometimes shares its results with google bot. I personnally experienced this many time on some of my (highly ranked) websites.
Here is some reading:
http://www.jensense.com/2006/04/16/adsense-mediapartners-bot-adding-to-the-google-search-index/
http://www.jensense.com/2006/04/18/matt-cutts-confirms-adsense-media-bot-in-natural-search-index/
http://searchenginewatch.com/article/2059088/Googles-Matt-Cutts-Confirms-AdSense-Bot-Helping-Googlebot-With-Indexing

So if the admin decides to put the link in the thank you page (Ie to allow users who've made an error in their email address to get a chance to access the ticket page), and if the thank you page contents some adsense code, it could potentially being indexed in the google search results.

Expiring the auth link will obviously not solve all problems, but because google crawls take weeks (for not too highly ranked websites) before appearing in the public results, having an expiration date lower than the average googledance time, will solve most of the issue....At least it's better than nothing...

BTW, I personally don't care if my TT would show up in Google, but as I saw that you seem worried about that, I just wanted to expose you some possible scenarios.

**Comment by protich** [comment]
I stand corrected on adsense bot - granted the post is 8 years old (Does it mean gmail emails (adsense supported) are getting indexed? I doubt it). Matt did reply within the comments to confirm that the bot will respect robot.txt. We'll add the noindex and nofollow.

That said, we can't control what _uninformed_ admin (developer wannabe really) does - after all osTicket is open source and not foolproof. As I mentioned in the previous reply - showing ticket ID is bad enough (if access is not restricted to single ticket view) even without indexing scenario.

My point was/is expiring the link and ticket ID (auth link is not the only issue by the way ) is not the solution. If the admin is dumb enough to expose the ticket ID or url - then what makes you think they'll enable the expiration and for how long? Should we enable ticket expiration by default? 

Adding noindex and nofollow will solve the possibility of google bot indexing - regardless of link exposure. Can other bots ignore the tags including caching the page forever? Yes.

Do we need to expire %auth_link and ticket ID? Possibly - but not for the sake of bots!

**Comment by soif** [comment]
> If the admin is dumb enough to expose the ticket ID or url - then what makes you think they'll enable the expiration and 
> for how long?

You're absolutely right :-D :-D

On the other hand why not use my #181 PR instead of the %auth link way.
It's totally bot proof (until bots start to follow javascript actions) and then also dumb-admins proof ;-)
What you think?

**Comment by soif** [comment]
BTW could someone please review or comment my #172 CSS PR (I'm gonna be on holiday in a few days, for 2 weeks, and I would like to be able to commit corrections -if needed- before I'll go away)

**Comment by protich** [comment]
The problem is javascript based auto-login can't be disabled at will by admin (it's a **baked** feature). With %auth based auto-logins -  an admin can enable or disable auto-login for one department based on template selection and not others. In addition, an optional captcha is planned for the login page for users who need an added security step.

**Comment by soif** [comment]
I could  have easily added:
 `if( $_GET['e'] && $_GET['t'] && $_GET['autologin'] && ! $cfg->GetCaptchaOnLoginIsEnabled )`
to solve both issues (while not enabling autologin on captcha enabled page)

But as you seems to really don't like the Javascript way and as I've currently no better idea, I will let you guys find a cleverer one!

**Comment by protich** [comment]
Can admin disable auto login on the fly (without having to edit the code) in your implementation? No - and that is the **primary** reason why we rejected it in favor of %auth based solution. The login captcha was not the determining factor.

**Comment by soif** [comment]
???
Of course  the admin can disable auto-login without changing the code: He just has to decide this in the templates:

In my previous code example, if the admin use a template containing a link with &autologin=1, then the form auto-login, if not (as in the current default templates) it does not auto-login.

Or did I miss something?

**Comment by protich** [comment]
None of your commits 84f85bb & 69d2910 or comments in (#180 & #181) had such implementation. Even "IF" you did implement it so, we would have rejected it. You seriously don't see the problem with using `autologin=1` vs `auth-code`? 
- Anyone can append autologin=1 to the url - I hope it crossed your mind!
- %auth code is unique and secure (server generated - user can't guess it) - this will help verify that the link was truly sent to the user.
- Since %auth validates the link - user will be able to by-pass captcha on login page (even when enabled)

**Comment by soif** [comment]
Ok I think you did not understand what I meant. Certainly my fault not explaining it correctly.
I will make the code so that you better understand...

**Comment by protich** [comment]
No need to waste your time or mine.

I was simply responding to the following statement.

> In my previous code example, if the admin use a template containing a link with &autologin=1, then the form auto-login, if not (as in the current default templates) it does not auto-login.

My comment was to the effect that you had **no such** "previous code example" or implementation. And even if you did, it'll still be rejected for the reasons I stated on my post.

**Comment by soif** [comment]
Ok I won't waste our time.
