### ISSUE TITLE
Auto Assign To Not Working

### ISSUE THREAD

**Issue by koolaide** [osTicket/osTicket-1.7#232]
Help Topics -> New Ticket Options - Auto-Assign TO:

I have selected different users but osTicket will not auto assign to anyone.

When you look at the Tickets tab in the Staff Panel the "Assigned To" header is blank. on every new ticket created that has a user assigned in the option listed above.

**Comment by greezybacon** [comment]
@koolaide, could you pull the code from #245 and retest this issue?

**Comment by slylenser** [comment]
I applied the code from #245 and it works.

Only the assigned team to a particular help topic receives emails now. Earlier - the entire department was receiving mails.
