### ISSUE TITLE
Rename file

### ISSUE THREAD

**Issue by mikhey54** [osTicket/osTicket-1.7#233]
osTicket-1.7 / include / client / kb-category.inc.php - > osTicket-1.7 / include / client / faq-category.inc.php

**Comment by mikhey54** [comment]
OR rename in:
kb/faq.php - line 31   ------>    $inc='faq-category.inc.php';
scp/faq.php   line 96  ------>    $inc='faq-category.inc.php';
kb.php - line 24  ------->      $inc='faq-category.inc.php';

**Comment by greezybacon** [comment]
My bad. I screwed that up in c938bef28718aab489e8b07c9560ae5523cfa947

**Comment by protich** [comment]
FYI: I did a hotfix on this one.

**Comment by greezybacon** [comment]
@mikhey54 can this be closed?

**Comment by mikhey54** [comment]
If you fix this then can be closed !!!
