### ISSUE TITLE
HTML Email Replies

### ISSUE THREAD

**Issue by AdeliavanTonder** [osTicket/osTicket-1.7#235]
Hi All.

I'm really a noob when it comes to php or any coding for that matter. Would you please consider to add a option for HTML email replies or notifications.  I understand the security risks to remove the striptags for HTML, but what about modding the code in order for notifications, alerts and messages from the system to be in HTML.

A simple layout like the one in this thread will be sufficient: http://osticket.com/forums/showthread.php?t=6777&highlight=html+replies

Problem is, I really do not know how to do this.  Can anyone assist me please?

**Comment by protich** [comment]
We plan on adding rich text support but it won't make v1.7 cut.

**Comment by greezybacon** [comment]
This is implemented in osTicket 1.8.0 and later. Thanks for the enhancement request
