### ISSUE TITLE
Timezone Issues

### ISSUE THREAD

**Issue by protich** [osTicket/osTicket-1.7#237]
Some users are reporting timezone related issues. It happens when MySQL timezone comes back as "SYSTEM" - meaning local timezone. The offset in such cases should be zero.

**Comment by slylenser** [comment]
I've found some issues related to timezone. 

The setting related to timezone in admin settings does not change the database config table. Despite this, staff panel tickets show the changed timezone while client panel shows the timezone based on database config table. Temp fix is to set the timezone in admin settings (say +5.5hrs for India) and then edit the config table in database and set timezone to 5.5 to match display in client and staff panels

**Comment by klimnad** [comment]
## Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Asia/Irkutsk' for 'IRKT/9.0/no DST' instead in /usr/share/doc/indexhtml/spravka/include/class.staff.php on line 61 

It is message i see when install the new clean - or upgrade. 
I solve this problem simply:
OR i was add in /include/class.config.php after line 51
date_default_timezone_set('Asia/Irkutsk');
Maybe it can be universal or automatic?
