### ISSUE TITLE
Attachments becoming corrupt at 1 MB filesize

### ISSUE THREAD

**Issue by josh1856** [osTicket/osTicket-1.7#240]
imap fetching when image (PDF) are sent in via email file is becoming corrupt.

Error reads:
"Adobe Reader could not open 'filename.pdf' because it is either not supported file type or because the file has been damaged (for example, it was sent as an email attachment and wasn't correctly decoded)."

**Comment by josh1856** [comment]
I have done some debugging and determined that regardless where the file is downloaded from (exchange/postfix/sendmail) the mail fetch is corrupting the files.  This is not happening to ALL files but only random which I have not been able to narrow down the specific issue.

**Comment by josh1856** [comment]
I have now tried pop3 and imap pulling from multiple sources and confirmed that the bug exists in both.

**Comment by josh1856** [comment]
The bug also occurs when you create a new ticket via the web portal.

**Comment by greezybacon** [comment]
I bet it only happens with attachments over 100k

**Comment by josh1856** [comment]
just tried 6 different files under 100kb and 6 over 100kb not all of them were corrupt over the 100kb

**Comment by josh1856** [comment]
corruption appears to be happening at 1MB

**Comment by greezybacon** [comment]
So my next guess is that AttachmentFile::save in the UPDATE statement, the second argument to the CONCAT function should be a BINARY string literal:

CONCAT(filedata, BINARY ' . db_input(...) . ')'

**Comment by greezybacon** [comment]
include/class.file.php

Sorry I don't have a line number

**Comment by josh1856** [comment]
what specifically needs to be changed?

**Comment by greezybacon** [comment]
Yeah, but you need a space between BINARY and the quote character

**Comment by josh1856** [comment]
like so?

```
            .' SET filedata = CONCAT(filedata, BINARY '.db_input($chunk) . ')'
```

**Comment by greezybacon** [comment]
Yes 

Am Aug 24, 2012 um 9:41 schrieb josh1856 notifications@github.com:

**Comment by josh1856** [comment]
Tried that and it doesn't appear to help with the 1MB files.

**Comment by greezybacon** [comment]
Can you send me an attachment that is getting corrupted? (jared at osticket dot com)

**Comment by josh1856** [comment]
I will send you one but it's pretty much any file above 1mb.

**Comment by josh1856** [comment]
any updates on this?

**Comment by josh1856** [comment]
I have verified that this issue also happens when you send an external (reply) to a ticket.

**Comment by greezybacon** [comment]
Hey @josh1856. I was able to upload the 2.4MB pdf file to a ticket and download it with no problems. Could you send me the mysql config (`SHOW VARIABLES`) so I can see if mysql is the culprit?

**Comment by josh1856** [comment]
My config is wide open I sent you a copy of the variables.  Also the corruption appears to be happening only with binary and ascii + binary files or images and pdf image+txt.  Normal ascii files are fine.

Is there some form of virus scanner or something that scrubs the files uploaded?

**Comment by josh1856** [comment]
I just installed osticket onto a completely different server and am able to replicated the corrupted image/binary and +ascii issues.

**Comment by josh1856** [comment]
another interesting fact:  the file size is showing up correct in the actual ticket but when you go to download it is a different file size.

test_file.jpg(3.2 mb) 

downloaded file size (1.0mb)

PDF's are random file sizes as well
