### ISSUE TITLE
Autoresponder Settings for "New Ticket by staff" reverts "Disable"

### ISSUE THREAD

**Issue by lhallberg** [osTicket/osTicket-1.7#268]
Autoresponder Settings for "New Ticket by staff" reverts to "0" or "Disable" when saving Alert and Notices settings.

I've traced this to the SQL UDATE in class.config.php on line 834:
.',ticket_notice_active='.db_input($vars['ticket_notice_active'])

It seems "ticket_notice_active" should not be set since the value is not submitted in the form.

**Comment by protich** [comment]
Fix for the bug is already in the works. We're also aware of auto response issues with staff created tickets - issue #269
