### ISSUE TITLE
Missing table on fresh install

### ISSUE THREAD

**Issue by jpoa** [osTicket/osTicket-1.7#270]
Greetings!

The table "ost_filter_rule" is not created with a fresh instal of the latest version (development) of v1.7.

In the setup the message displayed is "Error parsing SQL schema! Get help from developers (#4) osticket", as well as a SQL error reporting that the aforementioned table is not found. I have checked the database, and in fact it is missing.

Installing v1.6 and doing an upgrade worked flawlessly.

Best regards!

**Comment by protich** [comment]
Thanks for reporting the issue - a hot-fix (c89eb24) has been merged to develop.  The bug was introduced on a recent merge - I totally goofed on this one!
