### ISSUE TITLE
Warning: trim() expects parameter 1 to be string, array given in /include/class.filter.php on line 648

### ISSUE THREAD

**Issue by klimnad** [osTicket/osTicket-1.7#297]
This error exist from clean install of develop branch. Steps:
1. Install (on utf8 for russian) Database was created manual with utf8_general_ci.
2. Enabled helpdesk status
3. And when i ENABLE: ALLOW ATTACHMENTS - this error is started to showing - sorry for english.

where is error showing:
If i start to open new ticket  on index page I am enter these parameters of ticket:
1. full name on russian utf8
2. normal email.
3. simple telephone
4. help topic support
5. subject and message on russian
6. and add attachment 1 file .pdf
And here is error - when i click create ticket - on thankyou page i see 1 line with error at the top of screen:
Warning: trim() expects parameter 1 to be string, array given in /include/class.filter.php on line 648

After that i see the new ticket in admin panel - but if i try to delete this ticket - i have the new error: when i click to Are you sure to delete ticket OK - i see blank screen - omly white blank screeen no site no messages nothing - then i must to go to url address field of my browser and hit Enter on same page - it is ok i stay in admin and ticket was deleted. And i can continue to work.

I found the simple solution:
If i am turn off the "Allow attachments" then these 2 errors NOT EXIST.
And ticket i can create without message:
Warning: trim() expects parameter 1 to be string, array given in /include/class.filter.php on line 648
and that new ticket can be deleted from admin - and no white blank screen when i delete this ticket.

I think this problem exist only if ATTACHMENTS is enabled.
I hope this error will be solved, because it is good program - osticket.
But is is very need also upgrade the osticky extension for joomla - now it is only support osticket 1.6 and do not work with osticket 1.7. If will solve also this problem, then it is be very good.

Bye thanks for good program.
klimnad
Russia
Angarsk city

**Comment by protich** [comment]
Thank you for the report. A pull request (#296) with a fix is pending. It'll be merged to develop as soon as the review is completed.

**Comment by klimnad** [comment]
now i start to polling mail and NOT ALLOWED attachments but when cron is polling email through cron.php there is message appeared:
Fatal error: Call to undefined method AttachmentChunkedData::deleteOrphans() in /include/class.file.php on line 223
next i was ALLOWED attachments and send test email to mailbox and start polling and ticket was created like in my first message with errors - because have the attachments. 
I was thinked in email it will work - but i wrong still that problem.
Hope you solve it - i write 20000000 in size attachments - my server is 20m MAX. I also try smaller size and 10M and 1M still have the error.
Now i will try to use piping with attachments.
