### ISSUE TITLE
Tickets view only shows one ticket per page

### ISSUE THREAD

**Issue by greezybacon** [osTicket/osTicket-1.7#3]
In the staff control panel, Tickets page, only one ticket is displayed per page. So 4 tickets are displayed on the first page as

```
 Showing  1 - 1 of 4   Open Tickets
```

with three other pages

**Comment by protich** [comment]
- Installer need to set max_page_size=25  - fix will appear on the next push.

**Comment by greezybacon** [comment]
Fixed in be5bfa229589592cf0e27623fdbd6403b4ae1727
