### ISSUE TITLE
No Autoresponders - If i change the NAME of Default System Email with cirillic chatacters

### ISSUE THREAD

**Issue by klimnad** [osTicket/osTicket-1.7#301]
Hi
No Autoresponders - If i change the NAME of Default System Email (from)

Steps:
1. Turn on autoresponders it is work good with Email name of Default System Email with English characters, but i am russian and have the utf8 symbols. 
2. I test it - if name of Email from is in english it maybe Suppot or Support Service - it is all works. But when i was renamed it to utf8 characters with russian language like Служба Поддержки what means Support Service then i have FULLY stopped ALL autoresponders.
3. If i change the name "from" in Email name field back from russian to english - autoresponders is works again i tested 2 times - it is really.

**Comment by klimnad** [comment]
also impossible use email adress as name in Email from (sybmol @)

**Comment by protich** [comment]
@klimnad  - I'm assuming you've confirmed the issue is fixed? Thanks.

**Comment by klimnad** [comment]
Yes - issue is fixed - i was merged full last version of github osticket and it  is works now fine. Thanks.
