### ISSUE TITLE
Simple close ticket (without responding)

### ISSUE THREAD

**Issue by markcunninghamgit** [osTicket/osTicket-1.7#308]
There's the ability to close the ticket on response but why not have just the close button at the bottom without issuing a response. If you have a lot of tickets you don't want to have to try remember the name or number (especially if the names of tickets are very similar) and then go back to try find the right one then close it there.

**Comment by protich** [comment]
v1.6 had the functionality - we've reimplemented the feature for v1.7 (including ability to claim a ticket). See pull request #304.

**Comment by markcunninghamgit** [comment]
ah ok my apologies
