### ISSUE TITLE
OsTicket adding in = at the end of line

### ISSUE THREAD

**Issue by dgruhin** [osTicket/osTicket-1.7#329]
See copied email from OSTicket.

New ticket #218820 created.

---

Name: pdurrett@xxxxxxxxxx.org

Email: pdurrett@xxxxxxxxxxx.org

Dept: Support

Subject: pdurrett@xxxxxxxxxx.org wrote you a note

Hi there! You've received a message from a visitor while you were away. The=
y were on https://static.olark.com/jsclient/popout.html?_ok=6288-233-10-8=
730&wcsid=UzMyOaAnFW7Odg6WmFmKmXWE62882399&_oklv=1351023701114,UzMyOaAn=
FW7Odg6WmFmKmXWE62882399&hblid=l0AMFMKGURF7N9sbtr5GTFEO62882399&_okgid==
undefined&olfsk=olfsk14889817754738033&host=webapp.totalmanagement.com,=
referred to your site by http://www.totalmanagement.com/.

The user's message follows:

---

In the Woodruff Volunteer Center building there is a conflict between the a=
ccount balance of YMCA STG 9030-5 and the Accounts Receivable report. The A=
/R report states there is an outstanding amount of 0. But the tennant accou=
nt shows a zero balance. I think I know what happened. We were consolidatin=
g several units to one main billing account and I deleted previous charges.=
But it doesn't reflect on the A/R report. How can I get that report to ref=
lect the correct balance for 9030-5 YMCA (Woodruff Volunteer Center) to zer=
o?  Thanks,

Pat

**Comment by dgruhin** [comment]
Osticket is running on a centos 6.3 system, talking to Exchange 2010 via SMTP

**Comment by protich** [comment]
Try upgrading to RC3 and update us. We've addresses some email related encoding issues.

**Comment by greezybacon** [comment]
@dgruhin, any luck with RC3 or newer? Does the issue persist?

**Comment by greezybacon** [comment]
We switch to base64 encoding (instead of quoted-printable)
