### ISSUE TITLE
Error when adding new ticket

### ISSUE THREAD

**Issue by brunoscunha** [osTicket/osTicket-1.7#330]
For testing purposes I'm using xampp. When adding a new ticket with an image attached I get following error.
I'm using the latest RC
Fatal error: Call to a member function getSLAId() on a non-object in C:\xampp\htdocs\xampp\upload\include\class.ticket. php on line 711

function selectSLAId($trump=null) {
        global $cfg;
        # XXX Should the SLA be overwritten if it was originally set via an
        #     email filter? This method doesn't consider such a case
        if ($trump !== null) {
            $slaId = $trump;
        } elseif ($this->getDept()->getSLAId()) {
            $slaId = $this->getDept()->getSLAId();
        } elseif ($this->getTopicId() && $this->getTopic()) {
            $slaId = $this->getTopic()->getSLAId();
        } else {
            $slaId = $cfg->getDefaultSLAId();
        }
        return ($slaId && $this->setSLAId($slaId)) ? $slaId : false;
    }

**Comment by protich** [comment]
What version of PHP are you using?

**Comment by protich** [comment]
Another followup question: When you view the newly created ticket - does it have a department?

**Comment by brunoscunha** [comment]
My fault. Correted
