### ISSUE TITLE
1.7 RC3 - Deleting tickets.

### ISSUE THREAD

**Issue by cmpx** [osTicket/osTicket-1.7#349]
Just rolled into RC3 this morning from RC2, I went through my usual test of running a few tickets through the system to see what has changed and all was well, until I attempted to delete a ticket.  

The following error occurs whether the ticket is open or closed...

"Unknown or unsupported action - get technical help"

PHP 5.5.23, osTicket 1.7RC3-6c1f163

**Comment by protich** [comment]
Is this happening on mass delete or when you attempt to delete a ticket on view?

**Comment by cmpx** [comment]
This is happening on the mass ticket edit page.  However, attempting to delete the ticket in view mode results in nothing happening, there is no error, just nothing happens.

I just tested on multiple PCs and the issue seems to be specific to the Chrome browser(something I neglected to test before).  I receive a pop-up (as expected) when using IE9 and FF16.02, but not in Chrome (which is 23.0.1271.60) so maybe it's related to that?

**Comment by protich** [comment]
Thanks for the report & feedback. It's definitely JS related.

**Comment by fabiorauber** [comment]
Saw this happening too, but it was the browser cache, which was using old JS files.

**Comment by protich** [comment]
@fabiorauber I was just thinking it could be caching issue too. 

@cmpx - Can you do a forced reload and let us know the results?

**Comment by cmpx** [comment]
I was just testing and posting that. ;-)

A forced clearing of the cache resolves the issue, the pop-up now appears in both instances and allows the closing/deleting of tickets as expected.

Thanks

**Comment by protich** [comment]
@cmpx Whew! Glad that was the issue!  It'll probably make sense to add instruction for a forced reload, post upgrade. 

Thanks to both of you!

**Comment by cmpx** [comment]
No worries, thank you for the quick response.

Also, I was glad to see that the team functionality had been corrected in this release, thanks for that as well!

Take care.
