### ISSUE TITLE
Use Of mysql_*() Functions Which Will Be Deprecated In Future Releases

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket-1.7#361]
PHP developers will be phasing out mysql_*() functions in favor of the MySQLi and PDO extensions.
http://us2.php.net/manual/en/function.mysql-connect.php
https://wiki.php.net/rfc/mysql_deprecation
All documentation states that those functions should no longer be used.

The MySQL extension is no longer being maintained, and is becoming more and more less compatible with newer MySQL versions, and has numerous issues primarily security related that has led to the push to deprecate it.

This process will not happen overnight of course since so many packages still depend on it, but I suggest before OST becomes more complex that consideration be taken to migrate to one of the other extensions before it becomes too large of a task to perform. With the MySQL wrapper being used for OST this should not be that tedious of a task. I'll take a stab at replicating the wrapper in MySQLi. There are however a few other files that use mysql_*() functions which would need to be reviewed. Also since MySQLi is more secure in design some security checks would no longer be needed. That would have to be handled on a case by case basis. We have a long time before this happens, but better to start sooner than later in my opinion. =o)

**Comment by greezybacon** [comment]
v1.8 is planned to support multiple database platforms and move to the mysqli interface for mysql.

**Comment by ghost** [comment]
@greezybacon  is there a preference for OST to use MySQLi over PDO?
