### ISSUE TITLE
E-mail import fails when the ticket is rejected by a ticket filter

### ISSUE THREAD

**Issue by fabiorauber** [osTicket/osTicket-1.7#366]
When an e-mail arrives in an account used with osticket, and that ticket is rejected by a ticket filter, the e-mail fails to import, is not deleted, and the message of "too many errors" is logged every 10 minutes. Also, the ticket is denied every time and that message is also logged every 10 minutes. It would only go away when you delete the e-mail manually.

**Comment by greezybacon** [comment]
Can you recheck this with the above patch?

**Comment by fabiorauber** [comment]
Solved!
