### ISSUE TITLE
Change of Priority by user

### ISSUE THREAD

**Issue by JanKraljic** [osTicket/osTicket-1.7#381]
Have anyone already created some patch for user to be able to change Priority of ticket not just staff?

**Comment by protich** [comment]
It's a supported feature. Settings in Admin Panel > Settings Tab > Tickets > Web Tickets Priority

**Comment by JanKraljic** [comment]
Hi, 

i have just create fresh install of 1.7 and i cannot find how to change priority. User can set priority at new ticket but cannot change it later.

**Comment by JanKraljic** [comment]
Just submitted fix d7655d9fe2fc97acc7098540d6dbd4138d4393c1 in my fork
