### ISSUE TITLE
Assign template comments variable.

### ISSUE THREAD

**Issue by protich** [osTicket/osTicket-1.7#385]
Change %{message} to %{comments}

**Comment by thiagomonnay** [comment]
v 1.7

Friend I need help, I put the following variables in the template and I get the following result:

Template
%{assignee},

## Ticket #%{ticket.number} has been assigned to you by %{assigner}

## %{comments}

## New ticket #%{ticket.number} created.

Name: %{ticket.name}
Email: %{ticket.email}
Subject: %{ticket.subject}

%{message}

E-mail

-- do not edit --

%{assignee},

## Ticket #460567 has been assigned to you by %{assigner}

## %{comments}

## New ticket #460567 created.

Name: Thiago Monnay
Email: thiagomonnay@gmail.com
Subject: Gostaria de testar o envio de email

%{message}

---

Login to view complete details...

http://localhost/helpdesk/scp/tickets.php?id=12
