### ISSUE TITLE
PHP Deprecated - Function split() and  Assigning the return value of new by reference

### ISSUE THREAD

**Issue by mikhey54** [osTicket/osTicket-1.7#390]
PHP Deprecated:  Function split() is deprecated in /home/support/include/class.mailfetch.php on line 259
PHP Deprecated:  Assigning the return value of new by reference is deprecated in /home/support/include/pear/Mail/smtp.php on line 322

**Comment by protich** [comment]
What version do you have installed?

**Comment by mikhey54** [comment]
1.6.0 Stable

**Comment by protich** [comment]
Both issues already addressed in v1.7
