### ISSUE TITLE
Bug - Ticket reply using the gui removes characters

### ISSUE THREAD

**Issue by TechCare-Aus** [osTicket/osTicket-1.7#393]
Version 1.7RC3

Issue: Using the WebGUI and replying to a ticket with quoted amounts (e.g. $1400) would result in the first 3 characters being removed. What would show to the recipient via email is only 00.

I tried it with a different amount as well $1149 and it got stripped to 49

No other characters were removed. Seems that the character $ is causing this.

Please note that its only noticed on the email that is sent to the recipient, not on the WebGUI.

Regards,
Steven Swarts

**Comment by protich** [comment]
@sjswarts85 - The bug has been addressed in pull request #386.
