### ISSUE TITLE
Missing attachments with no other content in mail than attachment

### ISSUE THREAD

**Issue by Hamsteren** [osTicket/osTicket-1.7#398]
Hi,

I'm having an issue that i can reproduce. If i send a mail with no body only an attachment through imap then osTicket will pull the subject and name into a ticket and reply, but it wont attach the attachment just gets the text (EMPTY).
I have also tried setting the allowed filetypes to .\* but that makes no difference.
Tried enabling debug logging but it gave no hint of what happened.
It works fine if there is the slightest bit of text in the body.
This is tried with the newest version checked out from github.

Ubuntu 12.04
PHP Version 5.3.10-1ubuntu3.4
Apache/2.2.22 (Ubuntu)

**Comment by protich** [comment]
I'm unable to replicate the issue on my installation. What mail client are you using? Also, please send a sample email to peter @ osticket.com and cc support @ osticket.com.

Thanks,

**Comment by Hamsteren** [comment]
Sorry about the long response time, but i have sent you a couple of different mails as .eml files.
They both cause this issue.

**Comment by Hamsteren** [comment]
I tried a little debugging to see if i could help and this is what i get with a print_r on the $struct variable.
This is from a mail where it does not import the attachment:

```
stdClass Object
(
    [type] => 3
    [encoding] => 3
    [ifsubtype] => 1
    [subtype] => PDF
    [ifdescription] => 0
    [ifid] => 0
    [bytes] => 47410
    [ifdisposition] => 0
    [ifdparameters] => 0
    [ifparameters] => 1
    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [attribute] => name
                    [value] => IndkÃ¸bsordre 4500026964.pdf
                )

        )

)
```

And this one is from a mail where it does import the attachment:

```
[2] => stdClass Object
    (
        [type] => 3
        [encoding] => 3
        [ifsubtype] => 1
        [subtype] => PDF
        [ifdescription] => 0
        [ifid] => 0
        [bytes] => 585982
        [ifdisposition] => 1
        [disposition] => attachment
        [ifdparameters] => 1
        [dparameters] => Array
            (
                [0] => stdClass Object
                    (
                        [attribute] => filename
                        [value] => attachment.php.pdf
                    )

            )

        [ifparameters] => 1
        [parameters] => Array
            (
                [0] => stdClass Object
                    (
                        [attribute] => name
                        [value] => attachment.php.pdf
                    )

            )

    )
```

Dont know if this helps at all?

**Comment by protich** [comment]
Thanks for the debug info - it was very helpful. Pull request #449 addresses the issue.

**Comment by Hamsteren** [comment]
Glad i could help, but sadly it seems it's still not all attachments getting imported.
I have put some more examples on pastebin with $struct printed.
This one works:
http://pastebin.com/3FnUD7b4
The following does not:
http://pastebin.com/EkDEz9JL
http://pastebin.com/T8kaJAE5

If i can help with anything just let me know and i will try :)

**Comment by Hamsteren** [comment]
I've been looking into this issue as and it looks like this only happens when the mail has an attachment as the only content-type fx.
Content-Type: application/pdf; name="attachment.pdf"
Content-Description: attachment.pdf
Content-Transfer-Encoding: base64

If this is the case, then the ticket will say (EMPTY) and the attachment is "rejected".
It looks like the mailparser needs some check that says that if the body is empty it still needs to check for attachments (when content-type is not mulitpart)?

**Comment by Hamsteren** [comment]
Any progress on this? It's a big issue for us as we get about 40-50 order mails without a body and just a pdf attached.
I have looked into it some more and pulled out the $struct in class.mailfetch.php -> function getMimeType($struct)
And what i see is that on messages with a body that contains text or html you get:

```
stdClass Object
(
    [type] => 1
    [encoding] => 0
    [ifsubtype] => 1
    [subtype] => MIXED
    [ifdescription] => 0
    [ifid] => 0
    [bytes] => 71687
    [ifdisposition] => 0
    [ifdparameters] => 0
    [ifparameters] => 1
    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [attribute] => BOUNDARY
                    [value] => ------------AA2540BCF7E8B8D375E184D7
                )

        )

    [parts] => Array
        (
            [0] => stdClass Object
                (
                    [type] => 0
                    [encoding] => 0
                    [ifsubtype] => 1
                    [subtype] => PLAIN
                    [ifdescription] => 0
                    [ifid] => 0
                    [lines] => 3
                    [bytes] => 73
                    [ifdisposition] => 0
                    [ifdparameters] => 0
                    [ifparameters] => 1
                    [parameters] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [attribute] => CHARSET
                                    [value] => UTF-8
                                )

                        )

                )

            [1] => stdClass Object
                (
                    [type] => 3
                    [encoding] => 3
                    [ifsubtype] => 1
                    [subtype] => PDF
                    [ifdescription] => 0
                    [ifid] => 0
                    [bytes] => 71308
                    [ifdisposition] => 0
                    [ifdparameters] => 0
                    [ifparameters] => 1
                    [parameters] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [attribute] => NAME
                                    [value] => IndkÃ¸bsordre_90447.pdf
                                )

                        )

                )

        )

)
```

But on emails without the body you dont get an [parts] array just:

```
stdClass Object
(
    [type] => 3
    [encoding] => 3
    [ifsubtype] => 1
    [subtype] => PDF
    [ifdescription] => 1
    [description] => Po 4501617070
    [ifid] => 0
    [bytes] => 28996
    [ifdisposition] => 0
    [ifdparameters] => 0
    [ifparameters] => 1
    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [attribute] => NAME
                    [value] => Po 4501617070.pdf
                )

        )

)
```

I dont know if this is causing the issue and i'm just throwing it out as I am getting desperate to get this fixed.
It's a lot of manual labour to attach all the pdf's manually to the calls.

I have also testet with pop3 to see if it makes a difference it does not.

**Comment by briped** [comment]
Without having tested anything, I would hazard a guess that the problem are in the createTicket function. More specifically [line 430](https://github.com/osTicket/osTicket-1.7/blob/develop/include/class.mailfetch.php#L430).
If I'm reading the code right, then createTicket is not even entering the IF block where it saves attachments, because there's no "parts" array.

**Comment by Hamsteren** [comment]
I tried commenting out line 430 as suggested by briped. And look and behold the attachments now appear.
