### ISSUE TITLE
Issues with release 1.6 RC3 release 6c1f163 / 26.11.2012

### ISSUE THREAD

**Issue by simak111** [osTicket/osTicket-1.7#402]
For example when a customer opened a ticket he chose department "Support" but I ma not able to see the ticket although I am admin in the staff panel. In my notification email I see that the department is "Sales" . However if I login on behalf of him I see as department "Support". This is really an issue. With the previous stable version I was able to see all tickets regardless the chosen department by the customer.

One more thing - when a customer open a ticket I always see in the Staff panel "File Upload Error - Invalid file type for" even the customer hasn't tried to attach a file.

**Comment by protich** [comment]
I responded to the first part of your questions on the [forum](http://osticket.com/forums/showthread.php?t=9640). Attachment issue is addressed in pull request #406.
