### ISSUE TITLE
Help topic nesting issue

### ISSUE THREAD

**Issue by jeffchulg** [osTicket/osTicket-1.7#405]
Hi, I'm trying to create a help topic nested configuration in that way : 
Database Creation
   Oracle
   SQL Server
   MySQL

Database Copy
   Oracle
   SQL Server
   MySQL  

I get an error message which tells me that I can't create a second help topic with the same name. As it's a nested help topic, I'm not sure I should get this error....

**Comment by jeffchulg** [comment]
In addition, only one-level nesting is allowed (although it is customizable ?)

**Comment by protich** [comment]
You're absolutely correct on the error - it's a bug.

The system only allows one-level of nesting at the moment.
