### ISSUE TITLE
Show ticket's internal notes (and maybe attached files) separately 

### ISSUE THREAD

**Issue by jeffchulg** [osTicket/osTicket-1.7#408]
One thing which was great in ost 1.6 was to be able to accès directly to internal notes in ticket view. It has disappeared. 

One other thing, but it was a mod is to get the list of files uploaded in ticket view.

Do you think it'll be available in ost 1.7 (at least the first one)

**Comment by protich** [comment]
Option to show internal notes separately is in Admin Panel > Settings > Tickets.

**Comment by jeffchulg** [comment]
Yeah, I saw it afterwards... It's the reason why I closed the ticket.
