### ISSUE TITLE
No use of SSL when and after login

### ISSUE THREAD

**Issue by jeffchulg** [osTicket/osTicket-1.7#409]
All is in the title...

**Comment by protich** [comment]
This is outside the scope of osTicket - it's largely depends on web server. May be an option to force SSL but how useful will it be IF the server doesn't have certificate installed.

**Comment by greezybacon** [comment]
@jeffchlug, do you have a suggestion on how this should be addressed by the stock osTicket?

**Comment by jeffchulg** [comment]
actually, I've worked on this.. You can do it by configuring apache.
I used the virtual host feature and set that (through a rule) all incoming request on port 80 is redirected to port 443. The only point which misses is that you need a public ssl certificate (for the user not getting a warning and be obliged to add an exception to his navigator)

I could (but on february 18th) provide a sample of what I've done
