### ISSUE TITLE
Incorrect ticket URL in responses

### ISSUE THREAD

**Issue by OomJan** [osTicket/osTicket-1.7#421]
John doe,

Our customer support team personnel has replied to your support request #419494

xxxx

We hope this....

http://ticket.xxx.com/ticket.php?e=xxx@gmail.com&t=419494
## 

The URL points to "ticket.php" but that file does not exist. "tickets.php" does exist. I hope someone can fix this. Thank you for your time.

Sincerely
Kevin Gardthausen

**Comment by OomJan** [comment]
Tested with latest release as of Dec 16, 2012.

**Comment by protich** [comment]
The file is part of osTicket - you can confirm by browsing the code [here](https://github.com/osTicket/osTicket-1.7).

Perhaps you changed the Helpdesk URL in Admin Panel > Settings > System Preferences? The url is used to generate the links in email templates.

**Comment by whiteatom** [comment]
Do you have OSTicket installed in a folder under ticket.xxx.com?

**Comment by OomJan** [comment]
Good Day!

I found my problem in the e-Mail templates:

Changed: %{url}/ticket.php?e=%{ticket.email}&t=%{ticket.number}
To: %{url}/tickets.php?e=%{ticket.email}&t=%{ticket.number}

May have come from an older update or messed something up. Anyway thank for your prompt responses and support.

Sincerely
Kevin Gardthausen
