### ISSUE TITLE
Attachment directory setting does not exist

### ISSUE THREAD

**Issue by masinosinaga** [osTicket/osTicket-1.7#429]
I have been searching for Attachment directory setting in order to define/change the Upload directory, from Admin Panel -> "Settings" -> "Tickets" -> "Attachments" but I did not see the textbox for this. In 1.6 ST I could find it easily.

Did I miss something?

Running 1.7 RC4.

**Comment by Hamsteren** [comment]
Yes there is no attachment directory in 1.7, the files are stored in the database in the file table.

**Comment by masinosinaga** [comment]
Thanks for your info. I just tested the attachment feature by creating a ticket and uploading some files from client-side. The files seemed was uploaded successfully to the database (ost_file and ost_file_chunk tables). 

Unfortunately, when I was trying download the files either from client or staff side, I got always "attachment.php" file downloaded. 

Thoughts?
