### ISSUE TITLE
Saving 'Admin Notes' For A Team Does Not Work

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket-1.7#433]
I created a team, and then edited it and put in text in the 'Admin Notes' field and saved. It said it saved successfully, but the notes do not appear and checking database shows they do not save.

**Comment by protich** [comment]
Thanks for the feedback. Issue is now fixed on develop branch.

**Comment by greezybacon** [comment]
@protich you really should let the submitter close the ticket
