### ISSUE TITLE
Unrecognised charset breaks iconv() and prevents mail fetch

### ISSUE THREAD

**Issue by tjbp** [osTicket/osTicket-1.7#435]
MailFetcher::mime_encode() attempts to convert a body part, from the charset provided by the Content-Type header, to UTF-8. I have at least one email sent from Microsoft Office Outlook 11 that used the charset "x-user-defined" - in this instance for every body part in the email. This charset, and presumably infinite others, are not recognised by iconv().

Since iconv() returns false if the charset is not recognised, its return value needs to be checked (and mb_detect_encoding() called on failure). Not checking for failure causes the returned bool to be converted to a string, and in my case the email considered blank (and therefore not fetched).

**Comment by greezybacon** [comment]
Can you attach/include a raw, problem, example email?

**Comment by tjbp** [comment]
Here: https://gist.github.com/4419759

Please note I've removed sensitive data from a few headers as well as a few parts of the message body.
