### ISSUE TITLE
Change Email "Reply to" field

### ISSUE THREAD

**Issue by skaford** [osTicket/osTicket-1.7#447]
Is impossible to change the email REPLY TO field?

I need to change it and in this ne version this is imposibble, could you add this feature?

Because when I received the tickets from my website it have the mail: info@mysite.com and to answer my clients I need to change this response field with them email....

Could somebody tell me how to do it?

**Comment by protich** [comment]
This belong to the forum -  please post the question in the [forum](http://osticket.com/forums/forumdisplay.php?f=14) and I'll answer.

**Comment by skaford** [comment]
I did it Thank You
