### ISSUE TITLE
Problem In FAQ view/edition/creation --> Help Topics selection

### ISSUE THREAD

**Issue by jeffchulg** [osTicket/osTicket-1.7#458]
Hi, there is a problem in the help topics selection : it doesn't take into account the help topic nesting feature : 

Installation RDBMS
Installation RDBMS

Instead of 
Oracle/Installation RDBMS
SQL Server/Installation RDBMS

It's the same on the client-side...

**Comment by Richiricheh** [comment]
Where is this new feature in the dev branch? I cannot seem to find the option to nest FAQ/KB topics.

**Comment by protich** [comment]
@Richiricheh  huh? Help topics are nested in Admin Panel > Manage > Help topics. The pull request simply showed the nested help topics correctly - it's a bug fix not a new feature.

**Comment by Richiricheh** [comment]
apologies was doing a few too many things at once. I meant KB/FAQ topics. I was reading the pull req. 464. It was my understanding that it adds the ability to add nested KB/FAQ topics. I did not see where that option was in RC5

I should note that I have not read through that code in detail.
