### ISSUE TITLE
New Message Alert Emails

### ISSUE THREAD

**Issue by koolaide** [osTicket/osTicket-1.7#463]
When a user updates the ticket thread the feature "New Message Alert: Alert sent out when a new message, from the user, is appended to an existing ticket" is not sending out an email.

I have verified that when an internal note is added an email is sent.
![New Message Alert](https://f.cloud.github.com/assets/1271848/145926/c437877a-7477-11e2-8ce4-0151d4d66031.png)

**Comment by protich** [comment]
When you say user - do you mean client or staff?
