### ISSUE TITLE
Lost all ticket when I upgrade to 1.7-RC4

### ISSUE THREAD

**Issue by laguero** [osTicket/osTicket-1.7#465]
I upgrade osTicket from 1.6 ST to 1.7-RC4, the upgrade process was successful. But I just see 4 ticket in the staff panel. I have around 4500 record in the DB

**Comment by protich** [comment]
**First let's get the terminology right - you didn't loose ANY tickets they're still in the DB. You simply don't have permission to see them.** We did put in a lot of time and serious effort to make sure the upgrade process doesn't result in any data corruption or loss.

That out of the way - check and make sure the group you're assigned to has access to departments the tickets belong to. In v1.7 admin user type no longer have access to all tickets - permission has to be explicit at the group level.

**Comment by laguero** [comment]
Yes sorry for the title, and yes I did a select in the database and see the record, but when I login in the system no and also I dont know that OsTicket change the admin privilegies before I posted. So I did that you tell me and works thanks
