### ISSUE TITLE
Possible Detail Problem with Image

### ISSUE THREAD

**Issue by johndoeloldr** [osTicket/osTicket-1.7#51]
Hello.  I would just like someone to review this image.

Image from main client page:  http://prntscr.com/7v8rf

I'm not sure if the button has an extra space between "ticket" and "status".  It looks to me like there is an extra space, but I could be wrong.  I just thought I would have someone review this.  Thanks!

**Comment by kellishaver** [comment]
I've redone both landing page open ticket/check status buttons.
