### ISSUE TITLE
wrong function call in class.ticket.php: onOverdue()

### ISSUE THREAD

**Issue by belzael** [osTicket/osTicket-1.7#510]
There is a wrong function call in the file class.ticket.php on line 972:
            if($this->isAssigned() && $cfg->alertAssignedONTransfer()) {
it should be:
            if($this->isAssigned() && $cfg->alertAssignedONOverdueTicket()) {

**Comment by greezybacon** [comment]
Could you review this with the changes merged in the develop branch?

**Comment by belzael** [comment]
Looks alright to me.
