### ISSUE TITLE
Email Name Required when piping

### ISSUE THREAD

**Issue by bensuthers** [osTicket/osTicket-1.7#519]
If an email is sent to the API via external pipe that doesn't have a 'name', eg just an email address, the following error occurs. 

API Error (400)
Unable to create new ticket: validation errors:
name: Name required
err: Missing or invalid data - check the errors and try again
_[A7A3358288FAD9976DCC5F77FCD4AA09]_

**Comment by protich** [comment]
Thanks for the bug report - feel free to test above pending pull request or f32b35d.

**Comment by bensuthers** [comment]
Hey Peter,

Thanks.. I'm not familiar with the codebase, but that hasn't fixed my issue. 

I think, that maybe  you've fixed it for email_fetch... but I was piping an email in using automail,pl from an external server....

Thanks

Ben

**Comment by protich** [comment]
Ben - Are you sure you replaced both files? In your case it's class.mailparse.php

**Comment by bensuthers** [comment]
Thanks Peter! Of course, I hadn't. I didn't see the other file to replace.

It's all working fine now. Thank you very much.

Bug fixed!

**Comment by protich** [comment]
Thanks for the update - now I can go to sleep :) We'll get the fix merged to develop branch after a review.
