### ISSUE TITLE
Emails being cut off or coming over as {EMPTY}

### ISSUE THREAD

**Issue by bobuehlein** [osTicket/osTicket-1.7#522]
Hey all I'm using 1.7 RC6.

Many of our users emails come form outlook, as our company uses Exchange for Corporate email.

Many of our new tickets (checked via POP3) are coming across like

"Hi There," and nothing else, or they are coming in as {EMPTY}

The body of the (forwarded) message is at the following gist

https://gist.github.com/bobuehlein/5271360

It seems that things are being cut off after the =20 following the "Hey All,"

PLEASE HELP! :) I love OSTicket and would hate to have to look for something else.

**Comment by bobuehlein** [comment]
1.7 Final has fixed this...

**Comment by kbozi** [comment]
How you fixed this??? Please share.
