### ISSUE TITLE
 Internal Note Alert Email is sent back to the same person 

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket-1.7#537]
These are the settings under Alerts/Email

(x) Last Respondent
(x) Assigned Staff
(x) Dept Manager

Let's say I am a staff member who posted an internal note. In 1.7ST, the staff member who is NOT the last respondent, nor Assigned Staff, nor Dept Manager is getting the alert back.

From Peter (as a reminder): It happens when you respond to a ticket (thus becoming the last respondent) or when the ticket is assigned to you. Even with alerts enabled - you shouldn't get an alert when you post an internal note.
http://osticket.com/forums/showthread.php?t=13677&page=2

**Comment by protich** [comment]
Duplicate - see issue #535
