### ISSUE TITLE
API create call can't set department ID

### ISSUE THREAD

**Issue by BartVB** [osTicket/osTicket-1.7#551]
I love the fact that osTicket has an option to create new tickets through an API but this feature seems to lack a possibility to set the Department ID during creation. I'm using osTicket with several different queues (support/sales/etc) and need to be able to direct new tickets to the correct department. Changing the API to allow for deptID in API calls seems to be fairly trivial.

**Comment by ntozier** [comment]
Being able to assign department to a ticket your making via API does seem like something that you should be able to do.  That being said while your waiting for that to be implemented couldn't you setup ticket filters to assign the tickets to the department you want?

**Comment by BartVB** [comment]
That was the first workaround that I tried, but I don't see what criteria I can use to filter on. I would like to filter on recipient email (i.e. sales@example.com or support@example.com) but osTicket doesn't provide for that. Not in the API nor in the ticket filters. 
But thank you for the suggestion.

**Comment by protich** [comment]
The current API implementation is very basic - just mirrors the client interface at the moment. For now you can send in topicId - help topics can be mapped to departments in the backend.

**Comment by BartVB** [comment]
Ah, hadn't really looked at help topics yet. Seems to do almost exactly what I need, thanks!
