### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by edtownend** [osTicket/osTicket-1.7#558]
OK guys, this might seem a bit anal, but it's a serious question - what's the deal with having copyright messages in the footer of every page when LICENSE.txt says it's under a GNU public license? Basically, am I allowed to remove them?

Thanks! :-)

**Comment by greezybacon** [comment]
@edtownend, I'm no attorney, and perhaps I misunderstand both the question and the GPL, but GPL and copyright are two different things. The GPL license offers you the right to copy, modify, and distribute the osTicket software without fear of repercussion from the osTicket developers. Copyright defines the original owner of the source code. In this case the original owners are offering the software to you under the terms of the GPL, which coincidently gives you the right to modify the code and remove the copyright notices. At that point, if you redistribute the modified source code files, you are required to release them under the GPL or the copyright owners can legally pursue you.

Perhaps this discussion may help, http://news.slashdot.org/story/10/05/11/0151201/can-employer-usurp-copyright-on-gpl-derived-work

Cheers

**Comment by edtownend** [comment]
Brill, thanks for the explanation Jared.
