### ISSUE TITLE
 How to install [mod] HTML Email Templates in osTicket-1.7.0 

### ISSUE THREAD

**Issue by adeshsuryan** [osTicket/osTicket-1.7#560]
Hi , 
How to install [mod] HTML Email Templates in osTicket-1.7.0 .

I tried below path : 

class.config.php

class.email.php

Updating above two file in "include\" .

Updating below file at "include\staff" 
preference.inc.php

After that i got White screen , and/ or site down .

**Comment by protich** [comment]
Sorry but this is something you need to post in the forum.

**Comment by adeshsuryan** [comment]
Hi Protich ,
                    Actually i m looking for HTML Email Templates in osTicket-1.7.0 . 

I did some modification , now we can send html template rather then plane text.

**Comment by adeshsuryan** [comment]
Issue : Send HTML Email Templates Rather then plane Text .

After long debug , and modification i got solution of html template in OSTicket 1.7.0 .

Check the below solution :

Check " include" folder . and update the class.mailer.php class

Path : include/ class.mailer.php

Search : 
$mime->setTXTBody($body);
and replace by 

$mime->setHTMLBody($body);
