### ISSUE TITLE
'Open tickets' doesn't show  tickets assigned to me

### ISSUE THREAD

**Issue by BartVB** [osTicket/osTicket-1.7#561]
When I have 5 open tickets and one ticket has been assigned to me the 'open tickets' tab shows 4 tickets, the 'my tickets' tab shows one.

The list in 'my tickets' is correct, the fact that the ticket assigned to me is missing from the list of 'open tickets' is very counter intuitive.

**Comment by greezybacon** [comment]
There's a setting in the Admin Panel -> Settings/Tickets page:

Assigned Tickets:    Show assigned tickets on open queue.

Which controls, globally if assigned tickets are shown in the Open queue. There's also a similar setting in your _My Preferences_ if you are a manager which offers the same option, but specific for your account.

**Comment by BartVB** [comment]
Hmm, good one. Missed that setting. Thanks!
