### ISSUE TITLE
Integrate Reports Directly into osTicket

### ISSUE THREAD

**Issue by urda** [osTicket/osTicket-1.7#58]
osTicket should integrate the amazing report abilities of:

http://sudobash.net/ostickets-reports/

Instead of having to have the end installer hack it together.

**Comment by protich** [comment]
We're working on reports for v1.7 - but it won't be based on the link you provided.

**Comment by urda** [comment]
Ok thanks!

**Comment by rowdy2013** [comment]
Hello guys,

I am able to run the Reports under v1.7.
If anyone needs please pm me.

**Comment by BaroqueMed** [comment]
HI Rowdy2013

Can you please tell me how you got reports working on 1.7?

Thanks

**Comment by rmalpartidar** [comment]
POR FAVOR SEND ME A rmalpartidar@usmp.pe

**Comment by ntozier** [comment]
You can get the Reports module for 1.7 from:
http://www.sudobash.net/osticket-reports-6-0-osticket-release-1-7/
