### ISSUE TITLE
Add an option for saving attachments to folder (instead of database)

### ISSUE THREAD

**Issue by adriencarbonne** [osTicket/osTicket-1.7#584]
Hello,

I understand that starting with osTicket 1.7 attachments are stored in the database.
However, I do not understand the reasons which lead to this decision.

We have a production osTicket with _tons_ of attachments, and it really adds complexity to database management (duration and size of backups/restore, etc.).

Couldn't we have a settings to let the admin choose between folder and database?

Would it be enough to only modify the includes/class.attachment.php file, or are there references to the file/chunks tables in a lot of different source code files? (I am a PHP developer so maybe I can help?)

Thank you!

**Comment by edugargon** [comment]
10 months and no answer?... that's terrible.
Could you fix this issue?
I'm in the same situation. the system was installed on a rapsberry with v1.6 and after the v1.8 update, the SD was quickly filled and would like to reconfigure the attachments in an external hard drive. 
Thank you very much.

**Comment by greezybacon** [comment]
Drop the attitude. There is a storage-fs plugin for osTicket 1.8.1. Upgrade and install the plugin. There's also a cli script to migrate the attachments from the database to the location of choice on the filesystem. We've also recently released a plugin for Amazon S3 storage for plugins.

Cheers and your welcome

**Comment by edugargon** [comment]
thank you @greezybacon for your reply,
trying https://github.com/osTicket/core-plugins
cheers.

**Comment by ghost** [comment]
@greezybacon can you point me where that cli script is to migrate from db to fs?

**Comment by ghost** [comment]
Ohh its here: http://osticket.com/forum/discussion/77156/attachments-plug-in-storage-fs

**Comment by infectormp** [comment]
@adriencarbonne can you close this topic?
