### ISSUE TITLE
Captcha does not work with new ticket WHEN logged in as a client

### ISSUE THREAD

**Issue by urda** [osTicket/osTicket-1.7#59]
This is a current bug in the 1.6 release.

When captcha is turned on, and a client logs into an osTicket installation and then attempts to open a new ticket (logged in already) it will fail because the captcha is not presented to the end user.

This can be fixed by editing open/include/client/open.inc.php from this:

``` php
<?if($cfg && $cfg->enableCaptcha() && (!$thisclient || !$thisclient->isValid())) { 
```

With this:

``` php
<?if($cfg && $cfg->enableCaptcha()) { 
```

Which will show the captcha to the end user again when logged in.

Full details here: http://osticket.com/forums/showthread.php?t=3788

**Comment by protich** [comment]
Urda - Please let's limit issues to v1.7

**Comment by urda** [comment]
But as far as I can tell in the current code base this issue still exists in 1.7... Is this not the case on your end?

**Comment by protich** [comment]
That is not the case. Captcha is correctly NOT shown to logged in users. The issue in 1.6 was not the fact that the captcha was not shown - but the backed required it. In other words GUI worked as expected.

Thanks for the feedback.

**Comment by urda** [comment]
Ok, I'll need to check my test system to see what's up on my end. Thanks for the heads up!

**Comment by projenix** [comment]
Whether logged in or not captcha does not show on my system (image has "errors").
