### ISSUE TITLE
Header comments in class.log.php refer to class.group.php

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket-1.7#608]
Copy and paste error

**Comment by greezybacon** [comment]
Is this still valid? I don't see the erroneous comments in the latest develop branch

**Comment by ghost** [comment]
You are right. I used the localized installation V6 from Thane (see: http://www.osticket.com/forums/showthread.php?t=12514) and this one must have been forked before this was fixed in the main 3 month ago. I didn't think of that and should have checked before reporting.
