### ISSUE TITLE
Variable %{Company} in Email Template

### ISSUE THREAD

**Issue by pavel83** [osTicket/osTicket-1.7#641]
I added a custom field in in osticket and it's ok. But I want that field in email template. What must I do? Thanks

**Comment by pavel83** [comment]
I follow that link for add a customer field

http://www.tmib.net/adding-custom-text-fields-tickets

**Comment by greezybacon** [comment]
@pavel83, add a label to the switch statement in class.ticket.php in the `getVar()` function like this:

``` php
case 'company':
    return $this->getCompany();
```

Then you can use `%{ticket.company}`

**Comment by greezybacon** [comment]
@pavel83, were you able to get your custom working?

**Comment by pavel83** [comment]
Yes, it works perfectly.. Thanks!!!!

**Comment by franklynortega** [comment]
Hello, I need send to my agents when I assignation email, the Organization name an direction, 
but I don´t Know how do it?
