### ISSUE TITLE
Fatal Error at start of installation for site hosted on Windows UNC share

### ISSUE THREAD

**Issue by mr-brik** [osTicket/osTicket-1.7#649]
Hi,

I'm installing to a site hosted on a UNC share
 `\\host\share\example.org\example.org\web\content\ost`
 and I immediately get a 'Fatal Error' displayed.

The origin of the error seems to be the following two lines in client.inc.php:

```
 18 $thisdir=str_replace('\\\\', '/', realpath(dirname(__FILE__))).'/';
 19 if(!file_exists($thisdir.'main.inc.php')) die('Fatal Error.');
```

Where `realpath(dirname(__FILE__))` returns the string 
   `"\\host\share\example.org\example.org\web\content\ost"`
but str_replace returns
   `"/host\share\example.org\example.org\web\content\ost/"`
resulting in the Fatal Error when the main.inc.php file is not found.

I would've though that the str_replace() function is there to canonicalise 
Windows paths to their Unix counterparts, but in that case only
`str_replace('\\','/',$path)` would be necessary (which seems to resolve my 
issue), but am unsure of the purpose as, on Windows, PHP treats both \ and / as
a path separator. I accept the issue that UNC paths may not be truly absolute paths, but in the most part should be functional. A similar str_replace() operation occurs also in main.inc.php.

Hosting Details:
OS: Windows Server 2008 SP1
PHP: 5.2.14

**Comment by greezybacon** [comment]
I agree we should fix the issue as you describe. After talking it over, we don't remember what the `str_replace` call was added to correct or prevent.

I have to wonder, though, why would you setup a server this way?!

**Comment by mr-brik** [comment]
Hi,

I appreciate you looking it over, thanks for coming back to me.

Regarding your question(?) using UNC paths suggests files are being kept off the web server which makes sense for disaster recovery and general administration scenarios e.g. if you have a web server failure (the more vulnerable part of the system), you can more quickly recover by amending the configuration of a second web server more quickly than moving files [1]. The virtues of the UNC path though as a method to mount files are more debatable since it bears no reference to the client system, which immediately restricts client control and flexibility, and even MS core applications (e.g. cmd.exe) have incomplete/restricted support [2].

The application is hosted on shared hosting which I am not responsible for administering, so unfortunately I cannot provide the definitive rationale in this case.
1. http://www.iis.net/learn/web-hosting/planning-the-web-hosting-architecture/shared-hosting-configuration
2. http://support.microsoft.com/kb/156276

**Comment by greezybacon** [comment]
@mrscorpion, have you had a chance to retest since 1.7.1.3 was released?
