### ISSUE TITLE
Reports 4.3

### ISSUE THREAD

**Issue by rowdy2013** [osTicket/osTicket-1.7#66]
Guys,

You people made excellent Job.

Is there any chance we can add reports 4.2 code in Osticket 1.7 ??

I am getting error.

Appreciated your value feedback.

Thanks.Andrew

**Comment by protich** [comment]
The short answer is No. We'll build the reports for 1.7 from scratch since the data stores are substantially different.

**Comment by rowdy2013** [comment]
Hi Protich,

Thanks for your prompt reply.

Do you have any codes ? to get mini reports???

Thanks in Advance.

**Comment by protich** [comment]
Not at the moment.

**Comment by rowdy2013** [comment]
Hello protich.

I am sure you might be a export in PHP.

I have a sort query.

For reports we used play with header.inc.php

in version  header.inc.php file not able to see much different? strange something i am lacking.already i have added recommended reports code but no luck.

whts your opinion ?

**Comment by protich** [comment]
My opinion is - **you're wasting your time**. 1.7 code base is in development (will change without warning), in addition the database changes will most definitely render any 1.6 mods incompatible.

**Comment by rowdy2013** [comment]
:)

**Comment by rowdy2013** [comment]
Protich,

Thanks for your patience.

May i know the reports releasing date??? tentatively?
