### ISSUE TITLE
public page link now working

### ISSUE THREAD

**Issue by jeffchulg** [osTicket/osTicket-1.7#667]
Hi, I created a page called "test" and set its type to other. After I have saved, an url appeared. I clicked on it, and got a 404 error page.

**Comment by greezybacon** [comment]
@jeffchulg, which HTTP server are you using? Was this seen on the tip of the develop branch?

**Comment by jeffchulg** [comment]
Hi @greezybacon, I use the latest available version of apache server on a RHEL 5.8 default packages.
It was from OST 1.7.0 stock to 1.7.1 RC1

**Comment by greezybacon** [comment]
@jeffchulg, could you verify that the `.htaccess` file included in the source was uploaded to the `/pages` folder?

**Comment by jeffchulg** [comment]
hi @greezybacon , 
cd osticket/

ls | grep pages
==> nothing

so the pages directory has not been created.

**Comment by greezybacon** [comment]
@jeffchulg, thanks for the find. I fixed the bug in the packager. I think we're going to have to release an rc2 build since its hard to justify rolling bugfixes in and not bumping the version.

Perhaps you could manually copy these files from the repo to your server.

```
web.config
pages/.htaccess
pages/index.php
```

**Comment by jeffchulg** [comment]
I created manually those three files with their content on https://github.com/greezybacon/osTicket-1.7 
It worked perfectly.
Thank you.

**Comment by jeffchulg** [comment]
On the other hand, there is another problem : when I click on the public link of the site page in the admin interface. I get the page, but, when I come back to the admin and click on any link, I get the connection view.

**Comment by greezybacon** [comment]
@jeffchulg, I'm not following you. Could you post a screenshot? What's the 'connection view' and what are the links you're clicking on when you 'come back tot he admin'?

**Comment by jeffchulg** [comment]
For sure : So I clic public/test-php

![capture du 2013-08-22 07 26 38](https://f.cloud.github.com/assets/1788348/1006658/95310824-0aeb-11e3-8d22-0aa9aa11ab1d.png)

Then I come to this page :
![capture du 2013-08-22 07 28 19](https://f.cloud.github.com/assets/1788348/1006667/c3e85e4c-0aeb-11e3-824b-b859e169ee1f.png)

And finally go back to the osticket scp ( myosticket/scp )
![osticket16rc5scploginpa](https://f.cloud.github.com/assets/1788348/1014194/23c3984e-0bab-11e3-937c-8599262a8f87.jpg)

**Comment by greezybacon** [comment]
@jeffchulg, it looks correct to me. What am I missing?

**Comment by jeffchulg** [comment]
sorry, bad operation with image integration. Just updated my previous post :)

**Comment by jeffchulg** [comment]
there is still a problem here
