### ISSUE TITLE
Inaccurate XML API Documentation for Phone Numbers

### ISSUE THREAD

**Issue by andmatand** [osTicket/osTicket-1.7#670]
I was following [this documentation](https://github.com/osTicket/osTicket-1.7/blob/develop/setup/doc/api/tickets.md) to implement ticket creation via XML, and my requests were being rejected whenever I included a phone number. After some trial and error, I figured out that two parts of the documentation are inaccurate:

> phone_ext: Phone number extension -- can also be embedded in phone

and

> Notice that the phone extension can be sent as the @ext attribute of the phone sub-element.

What I found in practice was that the `ext` attribute _must_ be present if the `<phone>` tag is present at all; it is not optional and it also cannot be included in a separate `<phone_ext>` tag. I don't know if the documentation is worded badly, or just out of date, but it probably should be adjusted.

Anyway, thanks to whoever is responsible for this API; though basic, it is enabling our university to do some neat things on our website!

**Comment by greezybacon** [comment]
@andmatand, thanks for reporting the issue. The documentation posted was based on the concept, not the working software. The software should be corrected to work as the documentation specifies.

**Comment by greezybacon** [comment]
@andmatand, could I get you to retest your API submissions with the patch referenced above?

**Comment by andmatand** [comment]
Nice, I just tried it out and it now seems to work both without the extension and with it in a separate tag.
