### ISSUE TITLE
Adding attachments is not possible for normal users while creating a ticket

### ISSUE THREAD

**Issue by yafp** [osTicket/osTicket-1.7#675]
Hi,

i am not sure if thats on purpose or if its a bug or just undiscussed so far ;)

Our osTicket 1.7 installation doesnt allow normal users to add attachments while creating a new ticket.

so our workaround right now in such cases is as follows:
- user creates a ticket
- waits for the notification mail
- clicks the link in the mail 
- is now able to write a comment to this newly created ticket & attach a file if wanted.

From users point of view that workflow is somehow not perfect.

I guess if you thats on purpose to prevent spamming with attachments in a open accessible environment the best solution could be:
adding an option in the osticket administration to allow the admin to define if attaching files while creating a ticket is allowed or not.

Feel free to ask/discuss that idea further

Greetings
fidel

**Comment by ntozier** [comment]
You may want to provide some additional information regarding your setup
(server OS, webserver, php version, etc).  I am not able to replicate this
on my own installation and in fact I have a number of users that open new
tickets with attachments on a weekly basis.

**Comment by protich** [comment]
@macfidelity - This is not a bug. Make sure "Limit to authenticated users only" is unchecked in Admin Panel > Settings tab > Tickets

**Comment by yafp** [comment]
Hey,

@protich: perfect response. Unchecked that setting which i may have overlooked in the past.

Best regards
