### ISSUE TITLE
Valid CSRF Token Required

### ISSUE THREAD

**Issue by paulroots08** [osTicket/osTicket-1.7#677]
Hi,

I recently upgraded mine from 1.7 to 1.7.1 then I got "Valid CSRF Token Required", every time I login.

**Comment by greezybacon** [comment]
If you refresh the login page before logging in, does it work properly?

**Comment by sabas** [comment]
For me no...

**Comment by sabas** [comment]
@greezybacon why the token gets regenerated everytime?
Here fails the check imho

``` php
    function validateToken($token) {
        echo "validateToken".$token."<br>".$this->getToken();
        return ($token && trim($token)==$this->getToken() && !$this->isExpired());
    }
```

**Comment by greezybacon** [comment]
@sabas, are both sides changing? `$token` and `$this->getToken()` or just one?

Does this keep happening if you delete your browser cache and cookies and reload the page?

**Comment by sabas** [comment]
First questiion: the second one keeps changing (cause $token comes from the form I submit, the latter keeps generating from getToken() -trying with f5 and resubmit form-)
Second question: Yep tried now... (I've made a clean install to test, I didn't install inside my application as before)

Additionally these are both zero in is_expired, so returns always true...

``` php
echo $this->timeout."<br>";
echo (time()-$this->csrf['time']);
```

**Comment by greezybacon** [comment]
@sabas, is there a public URL to this osTicket install I could access to investigate this issue?

**Comment by sabas** [comment]
I try to get a working installation somewhere, could you contact me to my private email?

**Comment by sabas** [comment]
@greezybacon  YAY I get it, the issue is caused by local addresses (localhost), I connected via vpn to my workstation and scp is loading... Furthermore I loaded osticket on my website and works correctly...

**Comment by greezybacon** [comment]
@paulroots08, are you accessing osTIcket v1.7.1 via localhost as well?

**Comment by sabas** [comment]
Another test at work: via localhost => csrf error, via private ip from same machine (172...) => works.
