### ISSUE TITLE
How to un-assign a ticket

### ISSUE THREAD

**Issue by yafp** [osTicket/osTicket-1.7#682]
Hi,

is there a way in 1.7.0 to unassign an assigned ticket?

**Comment by greezybacon** [comment]
Department managers can release (unassign) tickets

**Comment by greezybacon** [comment]
We're wondering if we should extend the functionality to the group level so that any group (like Admins) could release a ticket

**Comment by yafp** [comment]
@greezybacon:
i do see a re-assign function - but not a release/unassign option in 1.7.0.

Opening it for admins sounds like a good option to me aswell btw.

**Comment by ntozier** [comment]
And by "admins" you actually mean any group with "Can _Assign_ Tickets"
enabled?

**Comment by greezybacon** [comment]
@macfidelity, are you a department manager -- check in the department settings, each department has a "Manager" setting. Ensure you're set to the department manager, then you can unassign the ticket

**Comment by yafp** [comment]
@greezybacon:
now i am the department manager ;) Looking backwards the main issue was realizing that only appartment-managers could do so && where osTicket would offer that option then.

I expected it to be on the same position where assignment itself is (ui-wise).

but ok - thats fine for me.

@ntozier:
i am fine with the current situation.

@all:
should i close the ticket or let it open based on the following comment

> > We're wondering if we should extend the functionality to the group level so that any group (like Admins) could >> release a ticket

best regards
fidel

**Comment by markus4000** [comment]
Extending to Grouplevel or to Adminlevel would be good. (i'm on 1.8.02)

**Comment by jjbridges** [comment]
I agree with markus4000.

**Comment by GeekSage** [comment]
I just ran into this issue as well (I'm an admin and couldn't assign the ticket).  This would definitely be very helpful.

**Comment by clonemeagain** [comment]
I wanted it on mine as well, I just changed line 148 of /include/staff/ticket-view.inc.php (osticket 1.10, edit sorry, didn't notice this was a 1.7 thread)

```php
if($ticket->isOpen() && ($dept && $dept->isManager($thisstaff))) {
```

to:
```php
if($ticket->isOpen() && ($dept && $dept->isManager($thisstaff) || $thisstaff->isAdmin())) {
```

Worked a treat. :-)

**Comment by webhead17** [comment]
@clonemeagain It was line 147 for me, but it worked like a charm! Thanks for that.

**Comment by yafp** [comment]
what should we do with this old issue?

**Comment by JediKev** [comment]
@yafp 

Being that this is pertaining to a version that is no longer supported and in a repo that isn't used anymore, I'd say Close this issue (I will close this for you actually). If you are using the `1.12.x` or the `1.14.x` series then there is either a global Role Permission to Unassign Tickets or if you are a Department Manager then you can Unassign any ticket in your Department.

Cheers.
