### ISSUE TITLE
 Issue with internal FAQ's

### ISSUE THREAD

**Issue by Richard-Regan** [osTicket/osTicket-1.7#683]
When we have been creating FAQ's, we have been using the flag internal and public. We noticed that when searching the FAQ's it would display all matches (public and internal) in its results list.

Is is true that users can only view public entries, but we did not want to expose even the headings of the internal FAQ's, therefore we had a look at the code.

We may have spotted a logic issue with your SQL statement within the knowledgebase.inc.php file.

if($_REQUEST['q'] || $_REQUEST['cid'] || $_REQUEST['topicId']) { //Search.
$sql='SELECT faq.faq_id, question '
.' FROM '.FAQ_TABLE.' faq '
.' LEFT JOIN '.FAQ_CATEGORY_TABLE.' cat ON(cat.category_id=faq.category_id) '
.' LEFT JOIN '.FAQ_TOPIC_TABLE.' ft ON(ft.faq_id=faq.faq_id) '
.' WHERE faq.ispublished=1 AND cat.ispublic=1';

if($_REQUEST['cid'])
$sql.=' AND faq.category_id='.db_input($_REQUEST['cid']);

if($_REQUEST['topicId'])
$sql.=' AND ft.topic_id='.db_input($_REQUEST['topicId']);

if($_REQUEST['q']) {
$sql.=" AND question LIKE ('%".db_input($_REQUEST['q'],false)."%')
OR answer LIKE ('%".db_input($_REQUEST['q'],false)."%')
OR keywords LIKE ('%".db_input($_REQUEST['q'],false)."%')";
}

$sql.=' GROUP BY faq.faq_id';

The issue is with the test for the search string, passed in a 'q'. The where clause restricts the matches by using the AND operator, and the search string uses the OR operator to check for matches within questions, answers and keywords.

The problem is that these two operators are at the same logical priority. Which results in anyway showing search string matches, the published state has no effect.

To remedy this just enclose the search string clause within brackets, as shown below.

if($_REQUEST['q']) {
$sql.=" AND ( question LIKE ('%".db_input($_REQUEST['q'],false)."%')
OR answer LIKE ('%".db_input($_REQUEST['q'],false)."%')
OR keywords LIKE ('%".db_input($_REQUEST['q'],false)."%') )";
}

I how this helps
Edit/Delete Message

**Comment by greezybacon** [comment]
Thank you for reporting this and finding the root cause.
