### ISSUE TITLE
Assigned SLA Plan cannot be changed after overdue

### ISSUE THREAD

**Issue by 7bp** [osTicket/osTicket-1.7#686]
I wanted to change the assigned SLA Plan for an overdue ticket but every time I do so it updates straight back to the old overdued SLA plan and sends out a new alert email.

In my case I have currently a 48h plan assigned and want to change it to a 9999h plan for internal purpose. Is this meant to not work?

Kindly Ben

**Comment by greezybacon** [comment]
@7bp, what version is this on? If you're on the develop branch or 1.7.1-rc1, is your Internal SLA set to Transient by chance?

**Comment by 7bp** [comment]
Oh, Im very sorry. I just recently switched to the developer branch and did not see this option in the SLA settings before, work splendid now. Mea culpa :-)
