### ISSUE TITLE
Typo in 1.7 - Post Internal Note - Summarry

### ISSUE THREAD

**Issue by yafp** [osTicket/osTicket-1.7#687]
Hi,

in case this wasnt reported before:  there is a small uncritical typo in 1.7

In the 'Post Internal Note'-tab i can see the following description:

> > Note title - summarry of the note (optional)  

I guess it should be

> > Note title - summary of the note (optional)

**Comment by greezybacon** [comment]
@macfidelity, thanks for reporting this. It was fixed in cd7c6cfa and will be released in 1.7.1
