### ISSUE TITLE
Upgrade to 1.7.1 causing cron script to spawn many processes

### ISSUE THREAD

**Issue by indusone** [osTicket/osTicket-1.7#704]
Hi

I just upgraded from 1.7.0 to 1.7.1 and my CPU is at 100% due to cron spawning at least 7 processes. I had to kill them manually and remove the cron entry in crontab.

**Comment by indusone** [comment]
PHP Warning:  strpos(): Empty delimiter in /var/www/support/include/class.misc.php on line 147

I got this warning in the system emails, maybe that will be of help.

regards,

**Comment by greezybacon** [comment]
@indusone, I posted a new download zipfile to address this issue this morning. You can either see if the pull-request suggested above fixes it or download the latest 1.7.1 build and see if it fixes the issue.

**Comment by greezybacon** [comment]
Thanks for posting the issue, by the way

**Comment by indusone** [comment]
Hi

I have replaced the contents of the file class.misc.php with your newer version and it has fixed the issue.

Thanks so much.
