### ISSUE TITLE
Can't login to admin panel

### ISSUE THREAD

**Issue by eddyuk** [osTicket/osTicket-1.7#721]
Right after installation, I go to http://localhost/funbox_ostickets/scp/index.php, enter username and password and getting return to login page with error Authorization required. Running Windows 8, IIS8 with URL Rewrite 2.0 installed. No php errors.
Ideas?

**Comment by mirekh** [comment]
Try read this tread:
https://github.com/osTicket/osTicket-1.7/issues/247#issuecomment-24437770

**Comment by greezybacon** [comment]
@eddyuk, are you still getting this error if you download the latest version from the osticket.com site (1.7.1.2)? There were several bugs fixed in the last two weeks concerning this issue.

**Comment by greezybacon** [comment]
@eddyuk, can I close this issue?

**Comment by eddyuk** [comment]
Yes, thanks for all answers. Just to let you know, the problem was that I misspelled site name in ost-config.php

while editing #define('ROOT_PATH', '/support/');

**Comment by greezybacon** [comment]
@eddyuk, good find! FYI, if you are able to upgrade to osTicket 1.7.1.4, you should be able to remove the edit to the ost-config.php file. Sorry for the confusion
