### ISSUE TITLE
Wrong title when edit Email templates 1.7.1

### ISSUE THREAD

**Issue by OleSta** [osTicket/osTicket-1.7#724]
When I go to /scp/templates.php?tpl_id=1 and select a template to edit they all have the same title "Autoresponse sent to user, if enabled, on new ticket." no matter which one I select.

In 1.7.0 there are no bug.

**Comment by greezybacon** [comment]
Thanks for reporting this! It was addresses in #727 and released in v1.7.1.3.

**Comment by OleSta** [comment]
Still a bug in 1.7.1.4.
Now the title is always: "Alert sent to staff on ticket transfer."
