### ISSUE TITLE
500 Internal Error in Forgot Password

### ISSUE THREAD

**Issue by elsonr** [osTicket/osTicket-1.7#725]
Hi,

Kindly help me solve this issue.
I am getting Error 500 in Forgot my Password page.
I am using osTicket latest version, IIS7.5 and Windows 2008 R2.
The error appears but the functionality still works. I still get a mail in my inbox and able to reset my password.
Below is the screen shot of the error.

![image](https://f.cloud.github.com/assets/4959271/1163054/7a260492-2032-11e3-9b76-0bf60341c962.png)

Regards,
Elson

**Comment by protich** [comment]
Do you see any specific errors in your IIS/PHP logs?

**Comment by elsonr** [comment]
Hi Protich,

I had enabled logging in IIS but unfortunately dint do that for Php.
After enabling the PhP logging to windows event viewer I am able to see this below screen

![phpostlogenable-error](https://f.cloud.github.com/assets/4959271/1165927/6bd9d28c-2074-11e3-90cd-12578854e8d5.jpg)

Here on the top I am able to see some error but yes the Error 500 has disappeared and the solution for it was enabling logging in php to syslog (event viewer in windows).

Regards,
Elson

**Comment by elsonr** [comment]
Error displayed in Event Viewer

The description for Event ID 2 from source PHP-5.4.19 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

php[3540]
PHP Warning:  mysql_result(): Unable to jump to row 0 on MySQL result index 67 in D:\support\upload\include\mysql.php on line 116
