### ISSUE TITLE
Installer expects MySQL password

### ISSUE THREAD

**Issue by ckdarby** [osTicket/osTicket-1.7#734]
Makes it impossible to use a mysql user with no password required without skipping the installer & doing it manually.

**Comment by ntozier** [comment]
The setup instructions clearly state that you should setup your mysql
database and user/pass first.  You should also never use a mysql user
account with out a password, its a huge security risk...

This is working as intended.

**Comment by ckdarby** [comment]
> You will need one MySQL database with valid user, password and hostname handy during installation. MySQL user must have FULL privileges on the database. If you are unsure whether you have these details or if the user has sufficient permissions, please consult your host or database admin before proceeding.

Doesn't state that a password is required and or that mysql NOPASSWORD is invalid.

> You should also never use a mysql user account with out a password, its a huge security risk...

Doesn't mean it isn't possible or that it is invalid and I wouldn't consider it a security risk outside of prod when user@localhost is only accessible by localhost along with the fact I'm using this in my dev environment which is why it is blank.

> This is working as intended.

That is all your reply needed to be..

**Comment by ntozier** [comment]
Your copy and paste clearly states "You will need one MySQL database with
valid user, password...".  I'm not sure why you would think that a password
would not be required when it says it is.

Using any type of account without a password is against all common security
security practices.

**Comment by kopitoshka** [comment]
I would agree with ckdarby. SQL password should not be required otherwise you can go further and check password strength, etc. People install the system on local servers and they need to do it fast under root mysql user without any passwords. It is annoying for me to remember what user I have with a password for mysql db.

**Comment by hbadass** [comment]
This is old but I found it quite annoying as well that I had to type in a password when using it in a development env. evt make a ?dev=true in the url. People who are setting this up usually know what they are doing

**Comment by AsheshMJoshi** [comment]
ya its annoying cause i am trying on my localhost... now i have to set password in mysql...
