### ISSUE TITLE
make phone size variable

### ISSUE THREAD

**Issue by jeffchulg** [osTicket/osTicket-1.7#735]
Hi,
If it's an internal ticket, the phone number can be of 4 digits. If the ticketing system is used in one country, the phone number size is not the same as another one.
Could it be possible to make a  change so that the phone number size is custom ?

**Comment by greezybacon** [comment]
I would vote for `wontfix` here. We're building in custom forms into osTicket 1.8, so you'll be able to change the phone number field to a simple number and use whatever size you would like.

**Comment by greezybacon** [comment]
@jeffchulg, would you mind reopening this against osTicket-1.8? I think I'd like to implement it against the configurable PhoneField and PhoneWidget shipped with custom forms and fields.

**Comment by clonemeagain** [comment]
@jeffchulg You can simply modify your own install.. it is "open source" after all! 

Input field: lines 88,90 & 99 of /include/staff/staff.inc.php specify the size of the input field. (phone,ext,mobile)
Database fields themselves are actually : 24,6,24 characters wide.. so I don't know why they went with: 18,5,18 for input.

The function: include/class.validator.php::is_phone actually limits phone values to 16 digits in length. (or less than 7)
Then the function include/class.format.php::phone has no limit, but formats numbers based on number of digits.

How many digits did you need?

**Comment by jeffchulg** [comment]
@clonemeagain thanks for the reply, it makes me think that this ticket has not been closed.
Actually, with the 1.8 and custom fields, it could be made, as @greezybacon suggests in his last post.
