### ISSUE TITLE
Ability to Create custom New Ticket pages and link to help topics - Enhancement

### ISSUE THREAD

**Issue by elsonr** [osTicket/osTicket-1.7#740]
Hi,

I will be grateful to you guys if a feature in osTicket can be added which will provision us to create new ticket pages which can be then linked to specific Help Topics.
The feature can help us to create custom pages with option to create mandatory custom fields and simple fields also.
We have issues related to hardware and the users logging ticket does not provide enough information like the laptop name, model & serial number hence this feature will compel them to provide all the required information. 

I don't know if there are any other ways to handle this issue. Please help me in this issue.

Regards,
Elson

**Comment by ntozier** [comment]
I think that you will find that the dynamic forms coming out in 1.8 will
suit your needs in this fashion.

**Comment by elsonr** [comment]
Thanks ntozier.. I will be waiting for this version to come.
