### ISSUE TITLE
Forward tickets to external email

### ISSUE THREAD

**Issue by OleSta** [osTicket/osTicket-1.7#746]
I would like to have the possibility to forward tickets to an external email.

Like this mod:
http://osticket.com/forums/showpost.php?p=43205&postcount=3

**Comment by protich** [comment]
CC/BCC is a feature we plan on adding to the core. Most mods in the forum are hacks with security holes -- see issue #506 for the challenges involved.

**Comment by OleSta** [comment]
I had not thought of the security hole - hiding the ticket ID (or part of it) on forward could be one solution or adding a secondary ID on forward not giving access to the ticket online.

**Comment by kaystrobach** [comment]
like to have forwarding as well ... additionally external answers should be added to the ticket ...

**Comment by szemy** [comment]
+1 to forwarding

**Comment by kanchanarandika** [comment]
+1 to the email forwarding feature

**Comment by adilix** [comment]
+1 please !

**Comment by seteq** [comment]
+1

**Comment by proudcommerce** [comment]
+1

**Comment by rahul10100** [comment]
+1

**Comment by fawaztahir** [comment]
+1

**Comment by FileSubmit** [comment]
+1

**Comment by digdilem** [comment]
+1 - still a problem!
