### ISSUE TITLE
Seperate "Staff Members" Page based on "Active" vs" "Locked" Status

### ISSUE THREAD

**Issue by urda** [osTicket/osTicket-1.7#75]
(Feature Request)

It would be great if I had another tab along the top of _Staff Panel > Staff_ so I can keep locked accounts out of sight, much like how "Closed" tickets are out of sight normally.

**Comment by greezybacon** [comment]
You can sort by [Status] which will push the 'Active' accounts to the top and the 'Locked' accounts to the bottom. Would that work for now?

**Comment by urda** [comment]
I don't see too much of a problem with that, but it may be in good interest to have the option to show only active staff members, as to reduce the size of the overall list. Basically so the end user can "Drill down" their query and see just the result.
