### ISSUE TITLE
HTML codes in Print (pdf)

### ISSUE THREAD

**Issue by OleSta** [osTicket/osTicket-1.7#756]
When printing ticket from 1.7.1.4 the Danish letters æøå, > and a few more is shown as html codes in the PDF.

**Comment by OleSta** [comment]
Can be fixed by changing line 96 in include/class.pdf.php
from:
return iconv('UTF-8', 'windows-1252', $text);
to:
return html_entity_decode(iconv('UTF-8', 'windows-1252', $text));

**Comment by greezybacon** [comment]
@OleSta, good catch. I agree with your fix. However, when I went to implement it, I'm conflustered. I have no idea why line 96 will transcode from utf-8 to windows-1252, and as an alternative, line 98 would transcode from iso-8859-1 to utf-8. Seems like they should do the same thing using different functions.

In a function named `_utf8` it would seem that the returned text should be utf8 formatted...

_I think there's more incorrect about line 96_

**Comment by OleSta** [comment]
FPDF fonts are using ISO-8859-1 or Windows-1252.
Line 98 is (still) doing the wrong thing and when I tested it gave a completely wrong characters.

**Comment by OleSta** [comment]
Line 98 should be changed
from:
return utf8_encode($text);
to:
return html_entity_decode(utf8_decode($text));

**Comment by OleSta** [comment]
Only thing left is to explain why the function is named _uft8 :)

**Comment by OleSta** [comment]
To be sure it works with PHP 5.4.0 and newer I think the function should look like:

```
function _utf8($text) {

    if(function_exists('iconv'))
        return html_entity_decode(iconv('UTF-8', 'windows-1252', $text), ENT_COMPAT | ENT_HTML401, 'cp1252');

        return html_entity_decode(utf8_decode($text), ENT_COMPAT | ENT_HTML401, 'ISO-8859-1');
}
```

**Comment by greezybacon** [comment]
There's another bug about Russian characters not being displayed in PDF output. I wonder if we should just switch to [mPDF](http://www.mpdf1.com/mpdf/index.php), use a font with a more complete unicode character set (like OpenSans), and just use utf-8 encoding directly

It also looks attractive, because HTML will be officially supported in osTicket/osTicket-1.8#5, and we'll need a way to print it
