### ISSUE TITLE
Overdue not flagged with cron on duedate

### ISSUE THREAD

**Issue by mcotterman** [osTicket/osTicket-1.7#757]
I found that in OSTicket 1.7.1 (downloaded on 10/2/2013) the overdue flag and notification where not sent on tickets where the duedate had passed.

When I looked in the checkOverride method of class.ticket.php I found that the SQL query seemed to be attempting to pull a list of tickets to flag overdue and one of the options was if the ticket's duedate had passed. In this case no SLA was set, so the inner join in the query was not allowing the ticket to return from the query as no SLA was assigned.

The Fix:

I changed the join in that query to a left join rather than an inner join and the tickets with duedates in the past that have not already been marked overdue and had no assigned SLA are processed as expected.

**Comment by greezybacon** [comment]
Thanks for finding the bug and the fix for this issue. Can you verity that I have mocked up the fix correctly in #767

**Comment by mcotterman** [comment]
Looks good!
