### ISSUE TITLE
Change of ticket SLA to None does not save

### ISSUE THREAD

**Issue by OleSta** [osTicket/osTicket-1.7#759]
If I change an overdue ticket SLA to None it just defaults to the SLA it was created with.

**Comment by greezybacon** [comment]
Do you have an SLA associated with the help-topic or department currently assigned to the ticket?

**Comment by OleSta** [comment]
I was not aware that a SLA was set up on the help-topic.
Setting the help-topic SLA to system standard fixed the problem.

**Comment by ckdarby** [comment]
@OleSta Glad to hear that solved your problem!

Can you close this issue, thanks =)!
