### ISSUE TITLE
Call to undefined method Email::lookupByEmail()

### ISSUE THREAD

**Issue by AlexeyDemidov** [osTicket/osTicket-1.7#766]
My api/cron.php started crashing few days ago with following error

PHP Fatal error:  Call to undefined method Email::lookupByEmail() in /var/www/{...deleted...}/osticket_1.7.0/upload/include/class.thread.php on line 547

My osTicket version is git checkout of 6603bfa545522f582396d4a3cfefcf9bd9c88a12

**Comment by greezybacon** [comment]
This is a known issue. It was addressed in 80e000a6 and released in 1.7.1.4. You should run a git pull and re-deploy

**Comment by AlexeyDemidov** [comment]
Sorry, my bad. I checked git history for fix but on wrong checkout.

**Comment by greezybacon** [comment]
So were you able to pull the fix into your repo?

**Comment by AlexeyDemidov** [comment]
I didn't have time to do full upgrade today so I just applied change from  80e000a  by hand.
