### ISSUE TITLE
Forgot Admin Password

### ISSUE THREAD

**Issue by KunalGautam** [osTicket/osTicket-1.7#785]
I've tried to reset my admin password, but seems like I'm unable to do so.
I've followed http://www.osticket.com/forums/forum/osticket-1-6-x/installation-and-setup-help/5450-admin-password-reset

**Comment by ntozier** [comment]
This should really be posted on the forums, not on github.  Github is for
tracking bugs and reporting issues with the software. That being said
please help us to help you by providing more information:

Version of osTicket?
Version of MySQL?
Version of PHP?
Are you getting any error messages when you run the mySQL query?
What is the actual query that you are using?

**Comment by KunalGautam** [comment]
Sorry for posting on Github,

Meanwhile I think I've found out how to reset admin password, go to http://<install domain and directory/scp/pwreset.php 

I was looking older solution which work for older installation of OSTicket.
