### ISSUE TITLE
character issue with subject and from name (UTF-8 issue?)

### ISSUE THREAD

**Issue by mtramp** [osTicket/osTicket-1.7#826]
include/class.mailfetch.php from 1.7.2

following funtion does not work correct in my environment
[code]
//Generic decoder - resulting text is utf8 encoded -> mirrors imap_utf8
function mime_decode($text, $encoding='utf-8') {

$str = '';
$parts = imap_mime_header_decode($text);
foreach ($parts as $part)
$str.= $this->mime_encode($part->text, $part->charset, $encoding);

return $str?$str:imap_utf8($text);
}
[code]

Sender name 'Test äüßxkàáte' is in osticket Test Ã¤Ã¼ÃxkÃ Ã¡te, same with the emails subject. However, the same text in email body works fine!

Raw data from email with error :
From - Tue Oct 29 12:19:56 2013
X-Account-Key: account8
X-UIDL: [snip]
X-Mozilla-Status: 0000
X-Mozilla-Status2: 00000000
X-Mozilla-Keys:  
Return-Path: [snip]
X-Original-To: [snip]
Delivered-To: [snip]
Received: by [snip](Postfix, from userid 33)
    id [snip]; Tue, 29 Oct 2013 12:19:45 +0100 (CET)
To: "[snip]" <[snip]>
Subject: Test äüßxkàáte
X-PHP-Originating-Script: 1000:email.php
From: "Test äüßxkàáte" <[snip]>
MIME-Version: 1.0
X-Mailer: php Mailer
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit
Message-Id: <[snip]>
Date: Tue, 29 Oct 2013 12:19:45 +0100 (CET)

Test äüßxkàáte

Here is a sample with the same text, but this one works fine. Subject and senders name is correct in osticket:
Message-ID: [snip]
Date: Tue, 29 Oct 2013 12:11:59 +0100
From: [snip] <[snip]>
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:24.0) Gecko/20100101 Thunderbird/24.0.1
MIME-Version: 1.0
To: [snip] <[snip]>
Subject: Test =?ISO-8859-15?Q?=E4=FC=DFxk=E0=E1te?=
Content-Type: text/plain; charset=ISO-8859-15; format=flowed
Content-Transfer-Encoding: 8bit

Test once again
äüßxkàáte
end test

**Comment by greezybacon** [comment]
I'll run your examples in a few cases and see if I can reproduce the errors internally.

However, you're example emails do not conform to the MIME RFC's. For instance, the top email has non-ascii characters in the headers "Subject" and "From" and perhaps others where [snip] is hiding the content. This is not valid MIME. The headers should be encoded as you have it in the second email with something more like the `=?ISO-8859-15?Q?...?=` text. You can read about "Encoded Word" syntax [here](http://tools.ietf.org/html/rfc2047) or [here](http://en.wikipedia.org/wiki/MIME)

Secondly, the body is encoded with "Content-Transfer-Encoding: 8bit", which is considered valid, but is not recommended, as many mail brokers will not transfer the mail correctly. It should be base64 or quoted-printable encoded so that the body is transmitted in us-ascii characters only. The Wikipedia page cited earlier alludes to this in the Content-Transfer-Encoding section.

Hope this helps

**Comment by mtramp** [comment]
greezybacon, thanks for taking care. The first sample (with the issue) was sent via oscommerce, a shop system we are using. From time to time we also get some emails from our users/customers causing the character issue in osticket. I have no sample at hand, but will post the raw data as soon as I noticed one.

The second email is from Thunderbird running on my personal computer.

**Comment by greezybacon** [comment]
Could you tell me if this function implementation decodes both emails correctly?

``` php
function mime_decode($text, $encoding='utf-8') {
    if (function_exists('iconv_mime_decode'))
        return iconv_mime_decode($text, ICONV_MIME_DECODE_CONTINUE_ON_ERROR, $encoding);

    $str = '';
    $parts = imap_mime_header_decode($text);
    foreach ($parts as $part)
        $str.= $this->mime_encode($part->text, $part->charset, $encoding);

    return $str?$str:imap_utf8($text);
}
```

**Comment by mtramp** [comment]
Test 1) still does nor work, but behavior changed:

Test äüßxkàáte  

becomes 

Test xkte 

All non-assci chars are lost.

Thank you for taking care!

**Comment by greezybacon** [comment]
``` php
function mime_decode($text, $encoding='utf-8') {
    if (function_exists('mb_detect_encoding'))
        if (($src_enc = mb_detect_encoding($text))
                && (strcasecmp($src_enc, 'ASCII') !== 0))
            return Format::encode($text, $src_enc, $encoding);

    $str = '';
    $parts = imap_mime_header_decode($text);
    foreach ($parts as $part)
        $str.= $this->mime_encode($part->text, $part->charset, $encoding);

    return $str?$str:imap_utf8($text);
}
```

How about this one?

**Comment by mtramp** [comment]
Perfect! Works in all test scenarios. 

Thank you for your great work.

**Comment by soneri** [comment]
Hi,

I am using Osticket 1.9.7 .. I upgraded from 1.8.? ..  I live in Turkey and i have problem with Turkish characters.

There were no problems before upgrading. Users send email with Turkish characters, but Osticket cannot decode.. I tried the solution in this page but did not work.

Can anynone help?

Regards

Soner
