### ISSUE TITLE
Date format "Due date"

### ISSUE THREAD

**Issue by StefaanVanDooren** [osTicket/osTicket-1.7#829]
When creating or editing tickets, the "Due date" field is always using amarican date notation, regardless what is defined in the settings.

**Comment by ntozier** [comment]
Generally when you post a bug report you should probably provide an example.  To me American date notation is either: 05 December 2013 or December 05, 2013 (taught in primary schools). The former being more used by University, Military, and legal documents, and the later being used on less formal documents.

Additionally I have tested this on my test box (which is running 1.8, as I do not have a 1.7.2 installation to test on currently) and I cannot confirm this bug.  When I go to the Admin panel and change the Date and Time options and then go view a ticket the due date is exactly what I expected it to be.  I change it back, and the display changes back.

**Comment by StefaanVanDooren** [comment]
12/31/2013 is what we/I call american, 31/12/2013 is European.
And you are right, when I view a ticket it is correct, but not when I edit or create one.
Look at the field "due date" in both images. first is in creation/editing, second is in view

![ticket_create](https://f.cloud.github.com/assets/5485451/1437464/06b988aa-416e-11e3-9dcf-23ec1fdf5050.jpg)
![ticket_view](https://f.cloud.github.com/assets/5485451/1437467/11f2504e-416e-11e3-9123-1b70e5b3f1e2.jpg)

**Comment by greezybacon** [comment]
Good catch @StefaanVanDooren

**Comment by StefaanVanDooren** [comment]
I still have a problem after patching my server.
due date error after I try to change the ticket

![ticket_after_codechange](https://f.cloud.github.com/assets/5485451/1438696/2a2e1852-4180-11e3-9586-3d27f13d9418.jpg)

**Comment by akash65** [comment]
can anyone tell me how due date is assigned once we create user through web portal?but here we didnot enter due date in any fields right then how it comes?

please help me asap

**Comment by ntozier** [comment]
@akash65  This does not appear to have anything to do with this error/issue report.  If you have general questions about how things work I would invite you to participate in the support forums at: http://osticket.com/forums

"Due Date" isn't assigned to users when they are created.  
Due Dates are assigned to Tickets.
Starting Due Dates are assigned by your Default SLA.

SLA's are managed at: Admin panel -> Manage -> SLA Plans.
Default SLA is at: Admin panel -> Settings -> Tickets.  this can be over ridden by departmental level SLA.
