### ISSUE TITLE
Invalid "due date"

### ISSUE THREAD

**Issue by StefaanVanDooren** [osTicket/osTicket-1.7#832]
issue #829 isn't fixed by the patched proposed in #830.
If you set the date format other than "m/d/Y", for instance "d/m/Y", you can now pick a date and it is correctly displayed, but on opening a new ticket or saving an altered one you get an error "Invalid due date" (see my last comment on #829)

I believe it comes from around line 1733 in include/class.ticket.php

elseif(strtotime($vars['duedate'].' '.$vars['time'])===false)
                $errors['duedate']='Invalid due date';

![image](https://f.cloud.github.com/assets/5485451/1440661/b92ec070-419d-11e3-96d3-725e551bb8d3.jpg)

**Comment by greezybacon** [comment]
Funny. I didn't try that format.
