### ISSUE TITLE
Email set up

### ISSUE THREAD

**Issue by Lisa003** [osTicket/osTicket-1.7#841]
Once i have received issues from people through os Ticket , i  seen them in the admin panel. Now when replying ot them so that they can get their ticket number, they dont get the e-mails.

How do i set this up.

Secondly the alert people to get the emails are not also alerted when a new ticket comes to the system, is this possible to happen

**Comment by ntozier** [comment]
This does not appear to be a bug report.  Please post a help topic on the forums or seek professional support. Oh and please close this error report.
