### ISSUE TITLE
when db schema is out of date, you can't add a new dept

### ISSUE THREAD

**Issue by binary64** [osTicket/osTicket-1.7#85]
when db schema is out of date, it shows a err splash on the page. which is fine, but the code that adds a new department is checking for anything, and not sending data to database, silently failing.

**Comment by protich** [comment]
If the db schema is out of date then you must complete the upgrade process before adding a new department.

I agree that it should error out with a more specific/verbose error related to the pending upgrade.

Thanks for the feedback.
