### ISSUE TITLE
Invalid CSRF Token __CSRFToken__

### ISSUE THREAD

**Issue by evanderv** [osTicket/osTicket-1.7#855]
This error is coming up when someone creates a ticket using IE.  There are no problems when we use FireFox.

**Comment by ntozier** [comment]
Which version of IE?

**Comment by evanderv** [comment]
IE9

**Comment by greezybacon** [comment]
Are you running osTicket in a frame?

**Comment by evanderv** [comment]
Yes I am

**Comment by greezybacon** [comment]
You can see osTicket/osTicket-1.7#774. You'll need to add a P3P header

**Comment by evanderv** [comment]
Got it.  All set.  Thanks!
