### ISSUE TITLE
AD (Active Directory) pass-through authentication

### ISSUE THREAD

**Issue by Richiricheh** [osTicket/osTicket-1.7#88]
For those using OSTicket as an internal helpdesk ticketing system having the users authenticate via AD would be a great option. This could allow the main page settings to include a list of open tickets with out the need to use email or ticket # to show that list. In addition,  pre-authenticating users this can allow the create new ticket screen to leverage pre-filled in fields making the creation of a new ticket just a bit faster.

**Comment by protich** [comment]
We plan on adding (optional) AD authentication to scp login.

**Comment by Richiricheh** [comment]
SO does this mean that SCP will be the only element of OS ticket slated for AD integration?

**Comment by protich** [comment]
Yes - for now. Client interface authentication needs some enhancements before AD integration - see issue #86 for my thoughts on user accounts.

**Comment by Richiricheh** [comment]
Makes sense. I plan on trying to have some custom dev work done and would like to contribute it back to the community. Perhaps you and I could talk so work I am looking to have done isn't already being completed by you or the other member(s) of the team?

**Comment by protich** [comment]
Sounds good to me - I'll be happy to give feedback and pointers. Simply create an issue with details on planned changes and the team will give you helpful feedback.

**Comment by Richiricheh** [comment]
I have code now for the index.php and client side ticket submission for AD pass-through. (at least my vision for it)

**Comment by arpitest** [comment]
Hi, im very interested in the modified index.php, as we have teh same requirements (clients submit tickets after AD auth, with pre-filled email department etc fields).

**Comment by greezybacon** [comment]
This is implemented in osTicket 1.8.1 with the auth-ldap and auth-passthru plugins
