### ISSUE TITLE
Valid CSRF Token Required

### ISSUE THREAD

**Issue by baidru** [osTicket/osTicket-1.7#881]
Hi,

I have face this kind of issue as same lot's of people faced.
i done with lot's of suggestion given by "greezybacon"
My osTicket Version is 1.7.0
please suggest me how to solved this.
i have also attached screen shot for the error screen
Thanks !

![www-tech-net-com-support-scp-login](https://f.cloud.github.com/assets/6582784/2074582/3553963c-8d7d-11e3-9ae5-081304ec8f51.png)

**Comment by rneha** [comment]
Hello

I simply added a redirection on the index.php and it worked.

Thanks

_Please consider the environment before printing this email_

**Comment by baidru** [comment]
Hi rneha,

 thanks for your kind support but 
where to add redirection can u please describe me.

**Comment by baidru** [comment]
Hello all,

session not set in live site that's why i am not able to login
In my osticket 1.7 url is
http://www.tech-net.com/support/scp/
in firebug i have checked (PHPSESSID means cookies) not set by server by the way  same code in my local working fine

please suggest me to solved this
Thanks!

**Comment by greezybacon** [comment]
Have you considered upgrading to 1.7.5? I think this may still be an issue. It will be difficult to address the issue if you're on such an old version, though.
