### ISSUE TITLE
cant attach more then 3 files in a single post

### ISSUE THREAD

**Issue by yafp** [osTicket/osTicket-1.7#888]
Hi,

i realized a bug in osTicket (v1.7.0) if it comes to attaching multiple files as part of an internal note.

In my installation i do see  'Browse' button which offers me the option to select a file to attach. This button is properly displayed as long as i have attached max 2 files in a single post.

BUT - and this is the ciritcal ugly big but here:
if i attach a third file in that specific single internal note - the 'browse' button disappears.

I haven't found an admin option to set an attachment limit - so i assume this is a bug.
Even if it would be an admin setting it would be better to display a notification at this particular point when the max amount of files per post are reached.

Sidenote:
Thats not a real issue for my special case - as i can workaround it until there is a fix for it - even if it takes a longer time BUT i was willing to report if back incase nobody else mentioned that behaviour already in the last weeks/months.

Greetings & thanks for your work on this project
fidel

**Comment by greezybacon** [comment]
There is a setting in Admin Panel -> Settings -> Tickets for the number of attachments that can be attached by either a staff or client. In other news, have you considered upgrading to something more current than 1.7.0? _We released 1.7.7 yesterday_

**Comment by yafp** [comment]
uh - i overlooked that setting in the admin-panel. 
Sorry for the ticket.

and yes - i do plan to update this installation, just need to find some time ;)

Sidenote:
i would still display a notification at that moment where you hide the Browse-Button.
This notification could just display 'amount of max attachments reached' or similar.

**Comment by greezybacon** [comment]
I agree. I think we should actually limit the total size of the attachments rather than the number of them anyway

**Comment by yafp** [comment]
Sounds like a good idea-  cause there aren't that much reasons to limit a user to i.e. 10 screenshots - if 11 might explain everything. On the other hand - i am pretty sure that some might argue the other way around ;)

My main point was more or less about giving the user a little bit more feedback (traceability) after hiding the browse button.
