### ISSUE TITLE
Adding a column to the ticket view

### ISSUE THREAD

**Issue by mtorres1** [osTicket/osTicket-1.7#890]
When you open a new ticket the form has a required selection for location - you have to pick the address. I would like for that to show on the ticket view so the supervisor can easily see which locations are requesting the most work - it will help him assign staff.

**Comment by greezybacon** [comment]
This issue concerns osTicket 1.8 or later, correct?

**Comment by mtorres1** [comment]
Yes, I am sorry I posted here - I reposted and was planning on comming back here and deleting this. I am using 1.8.0.2

**Comment by mtorres1** [comment]
i posted here http://osticket.com/forum/discussion/78421/using-osticket-v1-8-0-2-adding-column-to-ticket-view#latest
