### ISSUE TITLE
Wrong requirements for installation

### ISSUE THREAD

**Issue by lucamaro** [osTicket/osTicket-1.7#896]
Please update the php min version requirement: ternary operator "?:" is supported since php 5.3 and not 4.3. (see [http://php.net/manual/en/language.operators.comparison.php]).

Thanks.
Luca

**Comment by protich** [comment]
Where do we have the wrong min requirement listed?

**Comment by lucamaro** [comment]
There is a reference in setup/inc/install-prereq.inc.php, but probably even some code that performs the check. Today I was able to finish successfully the installation (on an old linux machine...), but not able to open login page.

**Comment by protich** [comment]
What version did you install? Latest version of osTicket requires PHP 5.3+

**Comment by lucamaro** [comment]
On our server we have PHP version 5.2.5 and a working installation of osticket 1.7 downloaded from the osticket site. There are two problems in my opinion: the first is that setup process should block installation when php < 5.3 is found. The second: just updating sources in 1.7 branch may break compatibility with your php. 

I have no problem in updating my outdated php, so feel free to close the issue. And thanks for your attention.

**Comment by protich** [comment]
Thanks for the feedback - I just wanted to get to the bottom of it. I think some of the bug fixes we back ported to 1.7 didn't take into consideration the PHP version requirements. We'll address the issue.
