### ISSUE TITLE
Embed video is not showing

### ISSUE THREAD

**Issue by Syedmudassar** [osTicket/osTicket-1.7#897]
I just change the following Format::display from Format::safe-html in (include-->client --> faq.category.inc.php) to view the images directly uploaded by the computer the src of the images is src="image.php?h=xikkr1swp24f7vd4i0bje6na01s1xtuq97819b1cb5a8bf3a9394ad27a9637db5" and they are showing properly but the problem is with the iframe video it is not showing the src is src="l.php?url=%2F%2Fwww.youtube.com%2Fembed%2F5dJKnuoC-eQ&amp;auth=699687c5cfedeabd6b942819dde2a642" 

Can any one help what I need to do to show video.

**Comment by Syedmudassar** [comment]
Solved need to add the authorization require('kb.inc.php');

**Comment by greezybacon** [comment]
> Solved need to add the authorization require('kb.inc.php');

Can you elaborate some more? I don't follow you

**Comment by karthikindia** [comment]
i dont understand this part, anyone can explain in detail
