### ISSUE TITLE
default text editor

### ISSUE THREAD

**Issue by Richiricheh** [osTicket/osTicket-1.7#90]
the default text editor has been significantly scaled back from v1.6. One of the items I liked about v1.6 was the ability to add an email link via a button in the text editor. This will be especially useful for the FAQ page. The older text editor for 1.6 had the ability to add pre-filled in fields as well such as send to email, Subject as well as email body.

**Comment by protich** [comment]
Not sure where you downloaded your version - but official v1.6 doesn't have rich text support. Perhaps it was a mod?

**Comment by Richiricheh** [comment]
I do not think it was a mod. I will post a screen cap for your reference. 

----- Original Message -----

**Comment by Richiricheh** [comment]
Hello Peter,

As it turns out you were correct. I didn't realize that one of the mods altered the text editor being used. A combination of mods appear to have changed OSticket's default text editor. The Rich text support came from OSFAQ's text editor. My suggested modification still stands simply because adding that rich text support will dramatically improve the knowledgebase in 1.7.

**Comment by yafp** [comment]
i agree- adding some kind of rich text editor (optional setting) would be great.

just as i am curious: any particular you would recommend?

**Comment by Richiricheh** [comment]
I apologize for not getting back sooner and not being able to put more time into getting a better response. The text editor which appears to be pretty good from my experience is the one which ships with OSFAQ. 

Screepcap: http://osfaq.oz-devworx.com.au/images/osfaq/screen_shots/edit-faq.jpg

**Comment by greezybacon** [comment]
osTicket 1.8 has a nicer rich text editor and support for rich text in the ticket thread
