### ISSUE TITLE
Staff Dashboard not populated

### ISSUE THREAD

**Issue by Richiricheh** [osTicket/osTicket-1.7#91]
When I have a staff member who has tickets assigned to them my staff tickets do not appears in the Staff dashboard. Subsequently my tickets do not show up in the Staff Dashboard either.

Setup: I am the departmental manager. I have 6 staff (not including me) Two of my staff and myself have tickets assigned to them.

**Comment by protich** [comment]
By default osTicket "hides" assigned tickets - it's not shown on the open queue. It's a feature that can be disabled in Admin panel > Settings tab > Ticket options by checking "Show assigned tickets on open queue".

**Comment by Richiricheh** [comment]
OK so I have now ticked that option as you suggested. The Dashboard is still blank. I am perhaps misinterpreting what the dashboard screen is meant for?

URL: <OSTICKET>/scp/dashboard.php

**Comment by protich** [comment]
It's planned for stats. As you know, v1.7 is in development with some features pending.

**Comment by intuen** [comment]
@protich Thank you this was very helpful.
