### ISSUE TITLE
Bad prefix. Must have underscore (_) at the end. e.g 'ost_'

### ISSUE THREAD

**Issue by rolltidehero** [osTicket/osTicket-1.7#925]
v. 1.14.2 installer continues to prompt me about the database prefix not ending with an underscore but it does. I left it at the default ost_ and it still throws the error. Screenshot below.

![image](https://i.imgur.com/VWjaLOS.png)

**Comment by JediKev** [comment]
@rolltidehero 

Wrong repo, please repost here:
- https://github.com/osTicket/osTicket

Also, I just installed osTicket v1.14.2 with PHP 7.4 and MySQL 8.0 today with no issues. Do you have a space at the end or something?

**NOTE:**
When you repost in the correct repo mentioned above please post your environment details such as PHP version, webserver version, MySQL version, etc.

Cheers.
