### ISSUE TITLE
Does anyone suggest a website chat system that can be integrated with osticket?

### ISSUE THREAD

**Issue by carlosdelfino** [osTicket/osTicket-1.7#929]
I need to implement a chat system on my website, but I wanted to have the option for it to be integrated with the sticket, it doesn't need many resources in this initial phase, just the data of whoever chats and based on this data inform the status of the ticket, and then Last case, based on the chat conversation, generate a new ticket.

Does anyone have any tips?

**Comment by JediKev** [comment]
@carlosdelfino 

1. This is the completely wrong repo. The correct repo is https://github.com/osTicket/osTicket.
2. This is more of a question. GitHub is used for reporting actual bugs/issues, to request new features, and to submit pull requests. It is not the place to ask general questions, etc. For that you should use the [Community Supported Forum](https://forum.osticket.com) instead.
3. We do not have any integrations with 3rd party chat bots/systems so, no, I cannot recommend any at this time.

Cheers.
