### ISSUE TITLE
Alerts & Notices Settings won't save...?

### ISSUE THREAD

**Issue by jfrux** [osTicket/osTicket-1.7#94]
All it says is "Unable to update system settings - correct any errors below and try again"

Any suggestions?

**Comment by jfrux** [comment]
[UPDATE ost2_config SET updated=NOW() ,ticket_notice_active='',ticket_alert_active='0',ticket_alert_admin=1,ticket_alert_dept_manager='0',ticket_alert_dept_members='0',message_alert_active='0',message_alert_laststaff=1,message_alert_assigned=1,message_alert_dept_manager='0',note_alert_active='0',note_alert_laststaff=1,note_alert_assigned=1,note_alert_dept_manager='0',assigned_alert_active=1,assigned_alert_staff=1,assigned_alert_team_lead='0',assigned_alert_team_members='0',transfer_alert_active='0',transfer_alert_assigned='0',transfer_alert_dept_manager=1,transfer_alert_dept_members='0',overdue_alert_active='0',overdue_alert_assigned=1,overdue_alert_dept_manager=1,overdue_alert_dept_members='0',send_sys_errors='0',send_sql_errors=1,send_login_errors=1]

Incorrect integer value: '' for column 'ticket_notice_active' at row 1

**Comment by protich** [comment]
Strict mode issue again! - it'll be addressed in the DPR4.

**Comment by greezybacon** [comment]
Strict mode setting pending in issue #100

**Comment by protich** [comment]
Session based strict mode now being set on db connect.
