### ISSUE TITLE
Creating a ticket

### ISSUE THREAD

**Issue by jfrux** [osTicket/osTicket-1.7#95]
[INSERT INTO ost2_ticket SET created=NOW()  ,lastmessage= NOW() ,ticketID=889227 ,dept_id=1 ,topic_id=2 ,priority_id=3 ,email='whatever@whatever.com' ,name='tester' ,subject='dfsa asfdasdfasdf' ,phone="" ,phone_ext='' ,ip_address='10.168.1.92' ,source='Web']

Field 'updated' doesn't have a default value

**Comment by protich** [comment]
Joshua - We'll look into the issue. For now you can turn off STRICT MODE in mysql.
