### ISSUE TITLE
Cannot print Tickets

### ISSUE THREAD

**Issue by leovipin1** [osTicket/osTicket-1.7#98]
Hi,

When I open a ticket and to print the ticket when i click on the print ticket button, it doesn't print the ticket.

kindly look into the same as well.

**Comment by protich** [comment]
Still in development... working on PDF export.

**Comment by greezybacon** [comment]
leovipin1, does the system print to your liking with the latest development snapshot?

**Comment by leovipin1** [comment]
The ticket is being exported in pdf and now able to print
